Build Mac OS X application bundle (.app).

diff --git a/bin/coin-config b/bin/coin-config
--- a/bin/coin-config
+++ b/bin/coin-config
@@ -19,6 +19,29 @@ me=`echo "$0" | sed 's,^.*[/\\],,g'`
 wd=`echo "$0" | sed 's,/[^/]*$,,'`
 prefix=`cd "$wd/.."; pwd`
 
+hello=`echo hello | fmt -t -w70 2>&1`
+if test x"$hello" = x"hello"; then
+  # 'fmt -t' works
+  preformat="fmt -t -w76"
+  sedformat='$ q; s/$/ \\/'
+else
+  # sed script replacing "fmt -w76 | sed '2,$ s/^/  /g; $ q; 1,$ s/$/
+  # \\/'"
+  preformat="cat"
+  sedformat='/^.................................................................+............/
+{
+  G
+  s/^\([^\
+]\{1,76\}\) \(.*\)\(\
+\)/\1 \\\3  \2/
+  P
+  D
+}'
+  if test xhello != x"`echo hello | sed -e $sedformat 2>&1`"; then
+    sedformat="s/a/a/"
+  fi
+fi
+
 usage="\
 Usage: $me [OPTIONS]
 Options:
@@ -87,7 +110,7 @@ do
       basename=`echo "$1" | sed -e 's/\.[^\.]*$//'`  # strip off extension
       # FIXME: SGI IRIX "fmt" doesn't support neither of the two options we use. 20021021 mortene.
       echo $compiler $CPPFLAGS $cppflags $CXXFLAGS $cxxflags -c $1 -o $basename.$objext \
-        | fmt -t -w76 | sed -e '$q; 1,$ s/$/ \\/'
+        | $preformat | sed "$sedformat"
       $compiler \
         $CPPFLAGS $cppflags \
         $CXXFLAGS $cxxflags \
@@ -105,11 +128,28 @@ do
     shift
     # FIXME: SGI IRIX "fmt" doesn't support neither of the two options we use. 20021021 mortene.
     echo $compiler $LDFLAGS $ldflags -o $progname $@ $libs $LIBS \
-      | fmt -t -w76 | sed -e '$q; 1,$ s/$/ \\/'
+      | $preformat | sed "$sedformat"
     $compiler \
       $LDFLAGS $ldflags \
       -o $progname $@ \
       $libs $LIBS || exit $?
+      case $host in
+      *-darwin*)
+        echo "$me: making Mac OS X application"
+        mkdir $progname.app 2>/dev/null
+        mkdir $progname.app/Contents 2>/dev/null
+        mkdir $progname.app/Contents/MacOS 2>/dev/null
+        if test -d $progname.app/Contents/MacOS &&
+          mv -f $progname $progname.app/Contents/MacOS/ &&
+          echo "APPL????" >$progname.app/Contents/PkgInfo; then
+          :
+        else
+          echo >&2 "$me: failed to make Mac OS X application"
+          echo >&2 " - problem is probably user permission or disk space related"
+          exit 1 
+        fi
+        ;;
+      esac
     exit 0
     ;;
   --build)
@@ -136,13 +176,30 @@ do
     done
     echo $compiler $LDFLAGS $ldflags $extraldflags \
       -o $progname $objs $extralibs $libs $LIBS \
-      | fmt -t -w76 | sed -e '$q; 1,$ s/$/ \\/'
+      | $preformat | sed "$sedformat"
     $compiler \
       $CPPFLAGS $cppflags \
       $CXXFLAGS $cxxflags \
       $LDFLAGS $ldflags $extraldflags \
       -o $progname $objs \
       $extralibs $libs $LIBS || exit $?
+      case $host in
+      *-darwin*)
+        echo "$me: making Mac OS X application"
+        mkdir $progname.app 2>/dev/null
+        mkdir $progname.app/Contents 2>/dev/null
+        mkdir $progname.app/Contents/MacOS 2>/dev/null
+        if test -d $progname.app/Contents/MacOS &&
+          mv -f $progname $progname.app/Contents/MacOS/ &&
+          echo "APPL????" >$progname.app/Contents/PkgInfo; then
+          :
+        else
+          echo >&2 "$me: failed to make Mac OS X application"
+          echo >&2 " - problem is probably user permission or disk space related"
+          exit 1
+        fi
+        ;;
+      esac
     exit 0
     ;;
   --setup)
