new gendsp system

diff --git a/cfg/gendsp.sh.in b/cfg/gendsp.sh.in
--- a/cfg/gendsp.sh.in
+++ b/cfg/gendsp.sh.in
@@ -6,49 +6,118 @@
 # file instead of the sources.
 #
 # It now also creates an installation script for the header files.
-#
-# The level of sed usage with ad-hoc quoting issue fixes in this script has
-# now officially reached the point of madness.  If developing this script
-# further, a complete rewrite to a more sensible language should be
-# considered seriously.
+# It also supports automatically moc'ing of source files, if certain
+# conventions are followed.
 #
 # TODO:
-#  - Defines should be verified:
-#     are WIN32 and _WINDOWS necessary?
-#     should _DEBUG be defined?
 #  - Indicate that the dsp file is *not* generated by Microsoft Developer
 #    Studio?  Will the MSVC++ IDE eat "foreign" dsp files?
 #
-# NOTES
-# * The large blocks of text were originally written as "cat >file <<EOF"
-#   blocks, but for some reason I still don't understand, that did not
-#   produce any input to file in the case of SoWin on Cygwin.  It worked
-#   for other cases.  It therefore had to be obfuscated into large
-#   echo "" >file blocks so it would work universally for all the projects.
-#
-# 20041214 larsa
+# 20050105 larsa
 
 me=$0
+
+
+# **************************************************************************
+# useful sed commands
+
+sed_d2u='s,\\,/,g' # dos2unix path delimiter switching
+sed_u2d='s,/,\\,g' # unix2dos path delimiter switching
+
+# **************************************************************************
+# useful autoconf variables - added for optimization/simplification reasons
+
+prefix="@prefix@"
+build_dir="@abs_top_builddir@"
+src_dir="@abs_top_srcdir@"
+ac_unique_file="@ac_unique_file@"
+sim_ac_relative_src_dir="@sim_ac_relative_src_dir@"
+sim_ac_relative_src_dir_p="@sim_ac_relative_src_dir_p@"
+
+me_u=`echo $me | sed $sed_d2u`
+medir_u=`echo $me_u | sed 's,[^/]*$,,g'`
+srcdir_u=`cd $medir_u/..; pwd | sed $sed_d2u`
+thisdir_u=`pwd | sed $sed_d2u`
+
+if $sim_ac_relative_src_dir_p; then
+  if test -f $srcdir_u/$sim_ac_relative_src_dir/$ac_unique_file; then
+    :
+    # things are in place
+  else
+    echo >&2 "$me: error: directories have been moved relative to each other"
+    echo >&2 "   since the last configure run."
+    exit
+  fi
+else
+  echo >&2 "$me: error: dsp generation is not supported when absolute paths"
+  echo >&2 "   are necessary to locate files."
+  exit
+fi
+
+# **************************************************************************
+# preliminary variable exploration
+
+# echo "me:       $me_u"
+# echo "medir:    $medir_u"
+# echo "srcdir:   $srcdir_u"
+# echo "thisdir:  $thisdir_u"
+
+# exit
+
 # run this where needed: me=`echo $me | sed 's%^.*/%%g'`
 
-if test x"$1" = x"--register-public-header"; then
-  sourcedir=$2
-  builddir=$3
-  studiofile=$4
-  headerfile=$5
-  # installpath=`CYGWIN= cygpath -w "$6" 2>/dev/null || echo "$6"`
+# **************************************************************************
+# The following block (the --registar-public-header part) generates
+# 1) the public headers part of the .dsp file
+# 2) the install*headers.bat file
+# It is invoked from a "make ... install-data"-command far down in this script
 
+if test x"$1" = x"--register-public-header"; then
+  studiofile=$2
+  headerfile=$3
+  installpath=$4
+  finalheader=`echo "$installpath" | sed -e "s,.*$prefix/\\(include\\|data\\)/,%COINDIR%/\\1/," -e "s,/\\./,/,g" -e "$sed_u2d"`
+  sim_ac_relative_src_dir_q=`echo "@sim_ac_relative_src_dir@" | sed -e 's,\.,\\\\.,g'`
+
+  # echo "========================="
+  # echo "source dir:   $src_dir"
+  # echo "build dir:    $build_dir"
+  # echo "install dir:  $installpath"
+  # echo "header:       $headerfile"
+
+  # echo "relative:     $sim_ac_relative_src_dir"
+
+  tested=true
   case $headerfile in
-  [a-z]:* | /* )
-    # absolute path
+  *$sim_ac_relative_src_dir/* )
+    headerfile=`echo $headerfile | sed -e "s%.*$sim_ac_relative_src_dir_q%$sim_ac_relative_src_dir%"`
     ;;
-  * )
-    # relative path
-    headerfile="`pwd`/$headerfile"
+  $build_dir/* )
+    tested=false
+    echo "EXPLICIT IN BUILD DIR"
+    headerfile=`echo $headerfile | sed -e "s%$build_dir/%%"`
+    ;;
+  $src_dir* )
+    tested=false
+    echo "EXPLICIT IN SOURCE DIR - CONVERT TO RELATIVE"
+    headerfile=`echo $headerfile | sed -e "s%$src_dir%$sim_ac_relative_src_dir%"`
+    ;;
+  *)
+    headerfile=`pwd`/$headerfile
+    headerfile=`echo $headerfile | sed -e "s%$build_dir/%%"`
     ;;
   esac
-  headerfile=`CYGWIN= cygpath -w "$headerfile" 2>/dev/null || echo "$headerfile"`
 
+  # echo "final header: $headerfile"
+  # echo "FINAL header: $finalheader"
+  # echo "========================="
+
+  headerfile=`echo $headerfile | sed -e "$sed_u2d"`
+
+  if $tested; then :; else
+    echo "untested case - manual inspection required";
+    exit 1;
+  fi
 
   echo "# Begin Source File" >>"$studiofile"
   echo "" >>"$studiofile"
@@ -58,16 +127,19 @@ if test x"$1" = x"--register-public-header"; then
   # and the installation script
   installheadersfile=`echo $studiofile | sed -e 's,\([^\\/0-9]*\)[0-9][^\\/]*\.dsp,install\1headers.bat,'`
 
-  sourcedirq=`echo "$sourcedir" | sed -e 's,\\\\,\\\\,g'`
-  builddirq=`echo "$builddir" | sed -e 's,\\\\,\\\\,g'`
-  relheader=`echo "$headerfile" | sed -e "s,$builddirq,.,g" -e "s,$sourcedirq,..\\\\..,g" -e 's,\\\\,\\\\\\\\,g'`
-  finalheader=`echo "$relheader" | sed -e 's,.*include,include,g'`
-  relheader=`echo "$relheader"`
-  finalheader=`echo "$finalheader"`
-  
-  echo "copy $relheader %COINDIR%\\$finalheader" >>"$installheadersfile"
+  # sourcedirq=`echo "$sourcedir" | sed -e 's,\\\\,\\\\,g'`
+  # builddirq=`echo "$builddir" | sed -e 's,\\\\,\\\\,g'`
+  # relheader=`echo "$headerfile" | sed -e "s,$builddirq,.,g" -e "s,$sourcedirq,..\\\\..,g" -e 's,\\\\,\\\\\\\\,g'`
+  # finalheader=`echo "$relheader" | sed -e 's,.*include,include,g'`
+  # relheader=`echo "$relheader"`
+  # finalheader=`echo "$finalheader"`
+
+  echo "copy $headerfile $finalheader >nul:" >>"$installheadersfile"
   exit 0
 fi
+
+# **************************************************************************
+#
 
 # this variable should contain the list of variables we want to use in the
 # project file setup, instead of just having the values.
@@ -294,8 +366,59 @@ if test x"$sourcefile" = x""; then :; else
   echo '!ELSEIF  "$(CFG)" == "'${library}@${LIBRARY}_MAJOR_VERSION@' - Win32 Debug"' >>"$studiofile"
   echo "# PROP Intermediate_Dir \"Debug\\$targetdir\"" >>"$studiofile"
   echo '!ENDIF ' >>"$studiofile"
-
   echo "# End Source File" >>"$studiofile"
+
+  if egrep "moc_.*.icc" "$sourcefileunixname" >/dev/null 2>&1; then
+    # The sourcefile needs MOC to be executed before building.
+    # The assumptions here are that the header is in the same directory in the
+    # hierarchy, and that the moc file contains the magic text telling the
+    # header file name.  It is also assumed that the moc file is not built
+    # on its own but included in the source file, and named moc_*.icc.
+    mocfile=`egrep "moc_.*.icc" "$sourcefileunixname" | sed -e 's,.*<\(.*icc\)>.*,\1,'`
+    mocfile=`echo $mocfile | sed -e 's,.*/,,'`
+    headerfile=`egrep "from reading C" $mocfile | sed -e "s,.*'\(.*\)'\$,\1,"`
+    mocfile="`pwd`/$mocfile"
+    mocfile=`echo $mocfile | sed -e "s%$build_dir/%%"`
+    mocfile=`echo $mocfile | sed -e "$sed_u2d"`
+    headerfilepath="`pwd`/$headerfile"
+    headerfilepath=`echo $headerfilepath | sed -e "s%$build_dir/%%"`
+    if test -f "$headerfile"; then
+      headerfile="$headerfilepath"
+    else
+      headerfile="$sim_ac_relative_src_dir/$headerfilepath"
+    fi
+    headerfile=`echo $headerfile | sed -e "$sed_u2d"`
+
+    echo "# Begin Source File" >>"$studiofile"
+    echo "" >>"$studiofile"
+    echo "SOURCE=$headerfile" >>"$studiofile"
+    echo "" >>"$studiofile"
+    echo '!IF  "$(CFG)" == "'${library}@${LIBRARY}_MAJOR_VERSION@' - Win32 Release"' >>"$studiofile"
+    echo "" >>"$studiofile"
+    echo "# PROP IgnoreDefaultTool 1" >>"$studiofile"
+    echo "#Begin Custom Build - moc'ing \$(InputPath)" >>"$studiofile"
+    echo "InputPath=$headerfile" >>"$studiofile"
+    echo "" >>"$studiofile"
+    echo "\"$mocfile\" : \$(SOURCE) \"\$(INTDIR)\" \"\$(OUTDIR)\"" >>"$studiofile"
+    echo "	\$(QTDIR)\bin\moc -o $mocfile $headerfile" >>"$studiofile"
+    echo "" >>"$studiofile"
+    echo "# End Custom Build" >>"$studiofile"
+    echo "" >>"$studiofile"
+    echo '!ELSEIF  "$(CFG)" == "'${library}@${LIBRARY}_MAJOR_VERSION@' - Win32 Debug"' >>"$studiofile"
+    echo "" >>"$studiofile"
+    echo "# PROP IgnoreDefaultTool 1" >>"$studiofile"
+    echo "#Begin Custom Build - moc'ing \$(InputPath)" >>"$studiofile"
+    echo "InputPath=$headerfile" >>"$studiofile"
+    echo "" >>"$studiofile"
+    echo "\"$mocfile\" : \$(SOURCE) \"\$(INTDIR)\" \"\$(OUTDIR)\"" >>"$studiofile"
+    echo "	\$(QTDIR)\bin\moc -o $mocfile $headerfile" >>"$studiofile"
+    echo "" >>"$studiofile"
+    echo "# End Custom Build" >>"$studiofile"
+    echo "" >>"$studiofile"
+    echo "!ENDIF " >>"$studiofile"
+    echo "" >>"$studiofile"
+    echo "# End Source File" >>"$studiofile"
+  fi
 fi
 
 case "$outputfile" in
@@ -311,12 +434,10 @@ case "$outputfile" in
   builddir=`echo "$studiofile" | sed -e 's%/[^/]*$%%'`
   builddir_unix=$builddir
   builddir=`CYGWIN= cygpath -w "$builddir" 2>/dev/null || echo "$builddir"`
-  builddirfixed=`echo "$builddir" | sed -e 's/\\\\/\\\\\\\\/g'`
 
   sourcedir=`echo "$0" | sed -e 's%/cfg/gendsp.sh$%%' -e 's,\\cfg\\gendsp.sh,,'`
   sourcedir_unix=$sourcedir
   sourcedir=`CYGWIN= cygpath -w "$sourcedir" 2>/dev/null || echo "$sourcedir"`
-  sourcedirfixed=`echo "$sourcedir" | sed -e 's/\\\\/\\\\\\\\/g'`
 
   # PUBLIC HEADERS
   # To get the list of public header files, we run "make install" into a
@@ -326,8 +447,10 @@ case "$outputfile" in
   echo '# Begin Group "Public Headers"' >>"$studiofile"
   echo "" >>"$studiofile"
   echo '# PROP Default_Filter "h"' >>"$studiofile"
-  ( cd $builddir_unix; make INSTALL_HEADER="$0 --register-public-header $sourcedirfixed $builddirfixed $studiofile" DESTDIR=/tmp/coin-dsp install-data )
-  rm -rf /tmp/coin-dsp
+  tmpdir=/tmp/dsp-install.tmp
+  ( cd $builddir_unix;
+    make INSTALL_HEADER="$0 --register-public-header $studiofile" DESTDIR="$tmpdir" install-data )
+  rm -rf $tmpdir
   echo '# End Group' >>"$studiofile"
 
   # PRIVATE HEADERS
