automatically integrate patches for using on/off shell variables in the AC_CONFIG_FILES macro

diff --git a/bootstrap b/bootstrap
--- a/bootstrap
+++ b/bootstrap
@@ -131,8 +131,9 @@ if $libtoolize; then
   )
 fi
 
-echo "Running autoconf (generating the configure script)..."
-( autoconf 3>&1 1>&2 2>&3 | grep -v AR_FLAGS) 3>&1 1>&2 2>&3
+# probably not necessary to run autoconf twice
+# echo "Running autoconf (generating the configure script)..."
+# ( autoconf 3>&1 1>&2 2>&3 | grep -v AR_FLAGS) 3>&1 1>&2 2>&3
 
 echo "Running autoheader (generating config.h.in)..."
 autoheader
@@ -140,6 +141,19 @@ autoheader
 echo "Running automake (generating the Makefile.in files)..."
 ( automake $AUTOMAKE_ADD 3>&1 1>&2 2>&3 | \
   grep -v 'not a standard library name' ) 3>&1 1>&2 2>&3
+
+if test -f configure.in.patch; then
+  echo "Patching configure.in with Automake-incompatible features..."
+  patch -p0 <configure.in.patch >/dev/null || { echo >&2 "failed" && exit 1 }
+fi
+
+echo "Running autoconf (generating the configure script)..."
+( autoconf 3>&1 1>&2 2>&3 | grep -v AR_FLAGS) 3>&1 1>&2 2>&3
+
+if test -f configure.in.patch; then
+  echo "Removing Automake-incompatibilities from configure.in again..."
+  patch -R -p0 <configure.in.patch >/dev/null
+fi
 
 echo "Done."
 
diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -16447,29 +16447,10 @@ fi
 
 # **************************************************************************
 
-# FIXME: this way of setting up vrml97 gives us a warning with
-# Automake -- which sucks. It also makes ``configure'' fail if vrml97
-# is not present -- which sucks ostrich eggs real hard.
-#
-# Since AC_CONFIG_FILES() takes everything in it's argument verbatim,
-# it's not possible to just set up a $VRML97MAKEFILE variable.
-# But we should really try to fix this.
-#
-# 20011014 mortene.
-
-# Don't commit with this as part of AC_CONFIG_FILES(), please.
-# ``configure'' won't work for those without the vrml97 extension
-# checked out.
-#        src/extensions/vrml97/src/Makefile
-
-# The fix for the above is to have the sub-modules as separate Autoconf-
-# projects and use AC_CONFIG_SUBDIR(src/extensions/vrml97) and the same
-# for superglu.
-# 20011023 larsa
-
-# NEW FIX:
-# while boostrapping, exchange $vrml97makefile with the explicit filename,
-# then replace with variable and rerun autoconf to update configure-script.
+# ATTENTION [20011120 larsa]
+# The Makefile list is now automatically patched by bootstrap before
+# Autoconf is run for a second time.  Make sure the bootstrap process works
+# without any error messages before you commit changes to this part.
 
 vrml97makefile=src/extensions/vrml97/src/Makefile
 if test -f $srcdir/${vrml97makefile}.in; then :; else
@@ -16557,7 +16538,7 @@ DEFS=-DHAVE_CONFIG_H
 : ${CONFIG_STATUS=./config.status}
 ac_clean_files_save=$ac_clean_files
 ac_clean_files="$ac_clean_files $CONFIG_STATUS"
-{ echo "$as_me:16560: creating $CONFIG_STATUS" >&5
+{ echo "$as_me:16541: creating $CONFIG_STATUS" >&5
 echo "$as_me: creating $CONFIG_STATUS" >&6;}
 cat >$CONFIG_STATUS <<_ACEOF
 #! $SHELL
@@ -16733,7 +16714,7 @@ cat >>$CONFIG_STATUS <<\EOF
     echo "$ac_cs_version"; exit 0 ;;
   --he | --h)
     # Conflict between --help and --header
-    { { echo "$as_me:16736: error: ambiguous option: $1
+    { { echo "$as_me:16717: error: ambiguous option: $1
 Try \`$0 --help' for more information." >&5
 echo "$as_me: error: ambiguous option: $1
 Try \`$0 --help' for more information." >&2;}
@@ -16752,7 +16733,7 @@ Try \`$0 --help' for more information." >&2;}
     ac_need_defaults=false;;
 
   # This is an error.
-  -*) { { echo "$as_me:16755: error: unrecognized option: $1
+  -*) { { echo "$as_me:16736: error: unrecognized option: $1
 Try \`$0 --help' for more information." >&5
 echo "$as_me: error: unrecognized option: $1
 Try \`$0 --help' for more information." >&2;}
@@ -16837,7 +16818,7 @@ do
   "docs/coin.doxygen" ) CONFIG_FILES="$CONFIG_FILES docs/coin.doxygen" ;;
   "default-1" ) CONFIG_COMMANDS="$CONFIG_COMMANDS default-1" ;;
   "include/config.h" ) CONFIG_HEADERS="$CONFIG_HEADERS include/config.h" ;;
-  *) { { echo "$as_me:16840: error: invalid argument: $ac_config_target" >&5
+  *) { { echo "$as_me:16821: error: invalid argument: $ac_config_target" >&5
 echo "$as_me: error: invalid argument: $ac_config_target" >&2;}
    { (exit 1); exit 1; }; };;
   esac
@@ -17150,7 +17131,7 @@ done; }
   esac
 
   if test x"$ac_file" != x-; then
-    { echo "$as_me:17153: creating $ac_file" >&5
+    { echo "$as_me:17134: creating $ac_file" >&5
 echo "$as_me: creating $ac_file" >&6;}
     rm -f "$ac_file"
   fi
@@ -17168,7 +17149,7 @@ echo "$as_me: creating $ac_file" >&6;}
       -) echo $tmp/stdin ;;
       [\\/$]*)
          # Absolute (can't be DOS-style, as IFS=:)
-         test -f "$f" || { { echo "$as_me:17171: error: cannot find input file: $f" >&5
+         test -f "$f" || { { echo "$as_me:17152: error: cannot find input file: $f" >&5
 echo "$as_me: error: cannot find input file: $f" >&2;}
    { (exit 1); exit 1; }; }
          echo $f;;
@@ -17181,7 +17162,7 @@ echo "$as_me: error: cannot find input file: $f" >&2;}
            echo $srcdir/$f
          else
            # /dev/null tree
-           { { echo "$as_me:17184: error: cannot find input file: $f" >&5
+           { { echo "$as_me:17165: error: cannot find input file: $f" >&5
 echo "$as_me: error: cannot find input file: $f" >&2;}
    { (exit 1); exit 1; }; }
          fi;;
@@ -17242,7 +17223,7 @@ for ac_file in : $CONFIG_HEADERS; do test "x$ac_file" = x: && continue
   * )   ac_file_in=$ac_file.in ;;
   esac
 
-  test x"$ac_file" != x- && { echo "$as_me:17245: creating $ac_file" >&5
+  test x"$ac_file" != x- && { echo "$as_me:17226: creating $ac_file" >&5
 echo "$as_me: creating $ac_file" >&6;}
 
   # First look for the input files in the build tree, otherwise in the
@@ -17253,7 +17234,7 @@ echo "$as_me: creating $ac_file" >&6;}
       -) echo $tmp/stdin ;;
       [\\/$]*)
          # Absolute (can't be DOS-style, as IFS=:)
-         test -f "$f" || { { echo "$as_me:17256: error: cannot find input file: $f" >&5
+         test -f "$f" || { { echo "$as_me:17237: error: cannot find input file: $f" >&5
 echo "$as_me: error: cannot find input file: $f" >&2;}
    { (exit 1); exit 1; }; }
          echo $f;;
@@ -17266,7 +17247,7 @@ echo "$as_me: error: cannot find input file: $f" >&2;}
            echo $srcdir/$f
          else
            # /dev/null tree
-           { { echo "$as_me:17269: error: cannot find input file: $f" >&5
+           { { echo "$as_me:17250: error: cannot find input file: $f" >&5
 echo "$as_me: error: cannot find input file: $f" >&2;}
    { (exit 1); exit 1; }; }
          fi;;
@@ -17383,7 +17364,7 @@ cat >>$CONFIG_STATUS <<\EOF
   rm -f $tmp/in
   if test x"$ac_file" != x-; then
     if cmp -s $ac_file $tmp/config.h 2>/dev/null; then
-      { echo "$as_me:17386: $ac_file is unchanged" >&5
+      { echo "$as_me:17367: $ac_file is unchanged" >&5
 echo "$as_me: $ac_file is unchanged" >&6;}
     else
       ac_dir=`$as_expr X"$ac_file" : 'X\(.*[^/]\)//*[^/][^/]*/*$' \| \
@@ -17545,7 +17526,7 @@ if test "$no_recursion" != yes; then
     # parts of a large source tree are present.
     test -d $srcdir/$ac_subdir || continue
 
-    { echo "$as_me:17548: configuring in $ac_subdir" >&5
+    { echo "$as_me:17529: configuring in $ac_subdir" >&5
 echo "$as_me: configuring in $ac_subdir" >&6;}
     case $srcdir in
     .) ;;
@@ -17567,7 +17548,7 @@ done; }
 
        if test -d ./$ac_subdir; then :;
        else
-         { { echo "$as_me:17570: error: cannot create \`pwd\`/$ac_subdir" >&5
+         { { echo "$as_me:17551: error: cannot create \`pwd\`/$ac_subdir" >&5
 echo "$as_me: error: cannot create \`pwd\`/$ac_subdir" >&2;}
    { (exit 1); exit 1; }; }
        fi
@@ -17598,7 +17579,7 @@ echo "$as_me: error: cannot create \`pwd\`/$ac_subdir" >&2;}
     elif test -f $ac_sub_srcdir/configure.in; then
       ac_sub_configure=$ac_configure
     else
-      { echo "$as_me:17601: WARNING: no configuration information is in $ac_subdir" >&5
+      { echo "$as_me:17582: WARNING: no configuration information is in $ac_subdir" >&5
 echo "$as_me: WARNING: no configuration information is in $ac_subdir" >&2;}
       ac_sub_configure=
     fi
@@ -17612,12 +17593,12 @@ echo "$as_me: WARNING: no configuration information is in $ac_subdir" >&2;}
         ac_sub_cache_file=$ac_dots$cache_file ;;
       esac
 
-      { echo "$as_me:17615: running $ac_sub_configure $ac_sub_configure_args --cache-file=$ac_sub_cache_file --srcdir=$ac_sub_srcdir" >&5
+      { echo "$as_me:17596: running $ac_sub_configure $ac_sub_configure_args --cache-file=$ac_sub_cache_file --srcdir=$ac_sub_srcdir" >&5
 echo "$as_me: running $ac_sub_configure $ac_sub_configure_args --cache-file=$ac_sub_cache_file --srcdir=$ac_sub_srcdir" >&6;}
       # The eval makes quoting arguments work.
       eval $ac_sub_configure $ac_sub_configure_args \
            --cache-file=$ac_sub_cache_file --srcdir=$ac_sub_srcdir ||
-        { { echo "$as_me:17620: error: $ac_sub_configure failed for $ac_subdir" >&5
+        { { echo "$as_me:17601: error: $ac_sub_configure failed for $ac_subdir" >&5
 echo "$as_me: error: $ac_sub_configure failed for $ac_subdir" >&2;}
    { (exit 1); exit 1; }; }
     fi
