Bootstrap

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -1027,7 +1027,6 @@ Optional Features:
                           [default=yes]
   --enable-3ds-import     enable 3ds import capabilities
   --enable-vrml97         enable VRML97 support
-  --enable-sound          enable sound support
   --enable-threads        enable platform-independent multithreading
                           abstraction classes
   --disable-w32threads    never use Win32 threads, even when available
@@ -1045,6 +1044,9 @@ Optional Features:
   --disable-loadlibrary   don't use run-time link bindings under Win32
   --enable-dl-simage      use runtime dynamic linking for libsimage if
                           possible [default=yes]
+  --disable-sound         disable sound support
+  --enable-dl-openal      use runtime dynamic linking for OpenAL if possible
+                          [default=yes]
   --enable-dl-glu         use runtime dynamic linking for GLU if possible
                           [default=yes]
   --enable-compact        enable hack for compact compilation [default=no]
@@ -1057,7 +1059,6 @@ Optional Packages:
   --with-msvcrt=<crt>     set which C run-time library to build against
   --with-gnu-ld           assume the C compiler uses GNU ld default=no
   --with-pic              try to use only PIC/non-PIC objects default=use both
-  --with-openal=PATH      enable/disable OpenAL support
   --with-pthread=DIR      pthread installation directory
   --with-doxygen=DIR      DIR is the directory where the doxygen executable
                           resides
@@ -1066,6 +1067,7 @@ Optional Packages:
   --with-dl=DIR           include support for the dynamic link loader library
                           [default=yes]
   --with-simage=DIR       use simage for loading texture files
+  --with-openal=PATH      enable/disable OpenAL support
   --with-x                use the X Window System
   --with-mesa             prefer MesaGL (if found) over OpenGL [default=yes]
   --with-opengl=DIR       OpenGL/Mesa installation directory
@@ -5021,7 +5023,7 @@ test "x$enable_libtool_lock" != xno && enable_libtool_lock=yes
 case $host in
 *-*-irix6*)
   # Find out which ABI we are using.
-  echo '#line 5024 "configure"' > conftest.$ac_ext
+  echo '#line 5026 "configure"' > conftest.$ac_ext
   if { (eval echo "$as_me:$LINENO: \"$ac_compile\"") >&5
   (eval $ac_compile) 2>&5
   ac_status=$?
@@ -5557,7 +5559,7 @@ chmod -w .
 save_CFLAGS="$CFLAGS"
 CFLAGS="$CFLAGS -o out/conftest2.$ac_objext"
 compiler_c_o=no
-if { (eval echo configure:5560: \"$ac_compile\") 1>&5; (eval $ac_compile) 2>out/conftest.err; } && test -s out/conftest2.$ac_objext; then
+if { (eval echo configure:5562: \"$ac_compile\") 1>&5; (eval $ac_compile) 2>out/conftest.err; } && test -s out/conftest2.$ac_objext; then
   # The compiler can only warn and ignore the option if not recognized
   # So say no if there are warnings
   if test -s out/conftest.err; then
@@ -7350,7 +7352,7 @@ else
     lt_dlunknown=0; lt_dlno_uscore=1; lt_dlneed_uscore=2
   lt_status=$lt_dlunknown
   cat > conftest.$ac_ext <<EOF
-#line 7353 "configure"
+#line 7355 "configure"
 #include "confdefs.h"
 
 #if HAVE_DLFCN_H
@@ -7448,7 +7450,7 @@ else
     lt_dlunknown=0; lt_dlno_uscore=1; lt_dlneed_uscore=2
   lt_status=$lt_dlunknown
   cat > conftest.$ac_ext <<EOF
-#line 7451 "configure"
+#line 7453 "configure"
 #include "confdefs.h"
 
 #if HAVE_DLFCN_H
@@ -8845,212 +8847,6 @@ if false; then
 else
   MAC_FRAMEWORK_TRUE='#'
   MAC_FRAMEWORK_FALSE=
-fi
-
-# Check if sound is enabled
-
-sim_ac_enable_sound=false
-
-# Check whether --enable-sound or --disable-sound was given.
-if test "${enable_sound+set}" = set; then
-  enableval="$enable_sound"
-
-  case $enableval in
-    yes) sim_ac_enable_sound=true ;;
-    *) ;;
-  esac
-fi;
-
-#  Check for openal (required for sound)
-
-: ${sim_ac_have_openal=false}
-echo "$as_me:$LINENO: checking for OpenAL" >&5
-echo $ECHO_N "checking for OpenAL... $ECHO_C" >&6
-
-# Check whether --with-openal or --without-openal was given.
-if test "${with_openal+set}" = set; then
-  withval="$with_openal"
-  case $withval in
-  yes | "") sim_ac_want_openal=true ;;
-  no)       sim_ac_want_openal=false ;;
-  *)        sim_ac_want_openal=true
-            sim_ac_openal_path=$withval ;;
-  esac
-else
-  sim_ac_want_openal=true
-fi;
-case $sim_ac_want_openal in
-true)
-  $sim_ac_have_openal && break
-  sim_ac_openal_save_CPPFLAGS=$CPPFLAGS
-  sim_ac_openal_save_LDFLAGS=$LDFLAGS
-  sim_ac_openal_save_LIBS=$LIBS
-  sim_ac_openal_debug=false
-  test -n "`echo -- $CPPFLAGS $CFLAGS $CXXFLAGS | grep -- '-g\\>'`" &&
-    sim_ac_openal_debug=true
-  # test -z "$sim_ac_openal_path" -a x"$prefix" != xNONE &&
-  #   sim_ac_openal_path=$prefix
-  sim_ac_openal_name=openal
-  sim_ac_openal_libs="-l$sim_ac_openal_name"
-  if test -n "$sim_ac_openal_path"; then
-    for sim_ac_openal_candidate in \
-      `( ls $sim_ac_openal_path/lib/openal*.lib;
-         ls $sim_ac_openal_path/lib/openal*d.lib ) 2>/dev/null`
-    do
-      case $sim_ac_openal_candidate in
-      *d.lib)
-        $sim_ac_openal_debug &&
-          sim_ac_openal_name=`basename $sim_ac_openal_candidate .lib` ;;
-      *.lib)
-        sim_ac_openal_name=`basename $sim_ac_openal_candidate .lib` ;;
-      esac
-    done
-    sim_ac_openal_cppflags="-I$sim_ac_openal_path/include"
-    CPPFLAGS="$CPPFLAGS $sim_ac_openal_cppflags"
-    sim_ac_openal_ldflags="-L$sim_ac_openal_path/lib"
-    LDFLAGS="$LDFLAGS $sim_ac_openal_ldflags"
-    sim_ac_openal_libs="-l$sim_ac_openal_name"
-#    sim_ac_openal_libs="-l$sim_ac_openal_name -alut"
-    # unset sim_ac_openal_candidate
-    # unset sim_ac_openal_path
-  fi
-  LIBS="$sim_ac_openal_libs $LIBS"
-  cat >conftest.$ac_ext <<_ACEOF
-#line $LINENO "configure"
-#include "confdefs.h"
-#include <AL/al.h>
-#ifdef F77_DUMMY_MAIN
-#  ifdef __cplusplus
-     extern "C"
-#  endif
-   int F77_DUMMY_MAIN() { return 1; }
-#endif
-int
-main ()
-{
-(void)alGetError();
-  ;
-  return 0;
-}
-_ACEOF
-rm -f conftest.$ac_objext conftest$ac_exeext
-if { (eval echo "$as_me:$LINENO: \"$ac_link\"") >&5
-  (eval $ac_link) 2>&5
-  ac_status=$?
-  echo "$as_me:$LINENO: \$? = $ac_status" >&5
-  (exit $ac_status); } &&
-         { ac_try='test -s conftest$ac_exeext'
-  { (eval echo "$as_me:$LINENO: \"$ac_try\"") >&5
-  (eval $ac_try) 2>&5
-  ac_status=$?
-  echo "$as_me:$LINENO: \$? = $ac_status" >&5
-  (exit $ac_status); }; }; then
-  sim_ac_have_openal=true
-else
-  echo "$as_me: failed program was:" >&5
-cat conftest.$ac_ext >&5
-fi
-rm -f conftest.$ac_objext conftest$ac_exeext conftest.$ac_ext
-  CPPFLAGS=$sim_ac_openal_save_CPPFLAGS
-  LDFLAGS=$sim_ac_openal_save_LDFLAGS
-  LIBS=$sim_ac_openal_save_LIBS
-  # unset sim_ac_openal_debug
-  # unset sim_ac_openal_name
-  # unset sim_ac_openal_save_CPPFLAGS
-  # unset sim_ac_openal_save_LDFLAGS
-  # unset sim_ac_openal_save_LIBS
-  ;;
-esac
-if $sim_ac_want_openal; then
-  if $sim_ac_have_openal; then
-    echo "$as_me:$LINENO: result: success ($sim_ac_openal_libs)" >&5
-echo "${ECHO_T}success ($sim_ac_openal_libs)" >&6
-
-  CPPFLAGS="$CPPFLAGS $sim_ac_openal_cppflags"
-  LDFLAGS="$LDFLAGS $sim_ac_openal_ldflags"
-  LIBS="$sim_ac_openal_libs $LIBS"
-
-cat >>confdefs.h <<\_ACEOF
-#define HAVE_OPENAL 1
-_ACEOF
-
-  if test x${sim_ac_configuration_settings+set} != xset; then
-  sim_ac_configuration_settings="OpenAL support:Yes"
-else
-  sim_ac_configuration_settings="$sim_ac_configuration_settings|OpenAL support:Yes"
-fi
-
-
-  else
-    echo "$as_me:$LINENO: result: failure" >&5
-echo "${ECHO_T}failure" >&6
-
-  if $sim_ac_enable_sound; then
-    { echo "$as_me:$LINENO: WARNING: openal is needed for sound" >&5
-echo "$as_me: WARNING: openal is needed for sound" >&2;}
-    sim_ac_enable_sound=false
-  fi
-  if test x${sim_ac_configuration_settings+set} != xset; then
-  sim_ac_configuration_settings="OpenAL support:No"
-else
-  sim_ac_configuration_settings="$sim_ac_configuration_settings|OpenAL support:No"
-fi
-
-
-  fi
-else
-  echo "$as_me:$LINENO: result: disabled" >&5
-echo "${ECHO_T}disabled" >&6
-
-  if $sim_ac_enable_sound; then
-    { echo "$as_me:$LINENO: WARNING: openal is needed for sound" >&5
-echo "$as_me: WARNING: openal is needed for sound" >&2;}
-    sim_ac_enable_sound=false
-  fi
-  if test x${sim_ac_configuration_settings+set} != xset; then
-  sim_ac_configuration_settings="OpenAL support:No"
-else
-  sim_ac_configuration_settings="$sim_ac_configuration_settings|OpenAL support:No"
-fi
-
-
-fi
-# unset sim_ac_want_openal
-
-
-HAVE_SOUND=1
-
-if $sim_ac_enable_sound ; then
-
-cat >>confdefs.h <<\_ACEOF
-#define HAVE_SOUND
-_ACEOF
-
-  if test x${sim_ac_configuration_settings+set} != xset; then
-  sim_ac_configuration_settings="Sound support:Yes"
-else
-  sim_ac_configuration_settings="$sim_ac_configuration_settings|Sound support:Yes"
-fi
-
-else
-  HAVE_SOUND=0
-  if test x${sim_ac_configuration_settings+set} != xset; then
-  sim_ac_configuration_settings="Sound support:No  (enable with --enable-sound)"
-else
-  sim_ac_configuration_settings="$sim_ac_configuration_settings|Sound support:No  (enable with --enable-sound)"
-fi
-
-fi
-
-
-
-
-if $sim_ac_enable_sound; then
-  BUILD_WITH_SOUND_TRUE=
-  BUILD_WITH_SOUND_FALSE='#'
-else
-  BUILD_WITH_SOUND_TRUE='#'
-  BUILD_WITH_SOUND_FALSE=
 fi
 
 # *******************************************************************
@@ -16562,6 +16358,243 @@ fi
 
 fi
 
+# Check if sound is enabled
+
+sim_ac_enable_sound=true
+
+# Check whether --enable-sound or --disable-sound was given.
+if test "${enable_sound+set}" = set; then
+  enableval="$enable_sound"
+
+  case $enableval in
+    no | false) sim_ac_enable_sound=false ;;
+    *) ;;
+  esac
+fi;
+
+#  Check for openal (required for sound)
+
+# Check whether --enable-dl-openal or --disable-dl-openal was given.
+if test "${enable_dl_openal+set}" = set; then
+  enableval="$enable_dl_openal"
+  case "${enableval}" in
+    yes | true) enable_dl_openal=true ;;
+    no | false) enable_dl_openal=false ;;
+    *)
+{ { echo "$as_me:$LINENO: error: invalid value \"${enableval}\" for \"--enable-dl-openal\" configure argument" >&5
+echo "$as_me: error: invalid value \"${enableval}\" for \"--enable-dl-openal\" configure argument" >&2;}
+   { (exit 1); exit 1; }; }
+ ;;
+  esac
+else
+  enable_dl_openal=true
+fi;
+
+if $sim_ac_enable_sound && $enable_dl_openal && $coin_can_do_runtime_linking; then
+
+cat >>confdefs.h <<_ACEOF
+#define OPENAL_RUNTIME_LINKING 1
+_ACEOF
+
+  if test x${sim_ac_configuration_settings+set} != xset; then
+  sim_ac_configuration_settings="OpenAL support:Yes, run-time binding"
+else
+  sim_ac_configuration_settings="$sim_ac_configuration_settings|OpenAL support:Yes, run-time binding"
+fi
+
+else
+: ${sim_ac_have_openal=false}
+echo "$as_me:$LINENO: checking for OpenAL" >&5
+echo $ECHO_N "checking for OpenAL... $ECHO_C" >&6
+
+# Check whether --with-openal or --without-openal was given.
+if test "${with_openal+set}" = set; then
+  withval="$with_openal"
+  case $withval in
+  yes | "") sim_ac_want_openal=true ;;
+  no)       sim_ac_want_openal=false ;;
+  *)        sim_ac_want_openal=true
+            sim_ac_openal_path=$withval ;;
+  esac
+else
+  sim_ac_want_openal=true
+fi;
+case $sim_ac_want_openal in
+true)
+  $sim_ac_have_openal && break
+  sim_ac_openal_save_CPPFLAGS=$CPPFLAGS
+  sim_ac_openal_save_LDFLAGS=$LDFLAGS
+  sim_ac_openal_save_LIBS=$LIBS
+  sim_ac_openal_debug=false
+  test -n "`echo -- $CPPFLAGS $CFLAGS $CXXFLAGS | grep -- '-g\\>'`" &&
+    sim_ac_openal_debug=true
+  # test -z "$sim_ac_openal_path" -a x"$prefix" != xNONE &&
+  #   sim_ac_openal_path=$prefix
+  sim_ac_openal_name=openal
+  sim_ac_openal_libs="-l$sim_ac_openal_name"
+  if test -n "$sim_ac_openal_path"; then
+    for sim_ac_openal_candidate in \
+      `( ls $sim_ac_openal_path/lib/openal*.lib;
+         ls $sim_ac_openal_path/lib/openal*d.lib ) 2>/dev/null`
+    do
+      case $sim_ac_openal_candidate in
+      *d.lib)
+        $sim_ac_openal_debug &&
+          sim_ac_openal_name=`basename $sim_ac_openal_candidate .lib` ;;
+      *.lib)
+        sim_ac_openal_name=`basename $sim_ac_openal_candidate .lib` ;;
+      esac
+    done
+    sim_ac_openal_cppflags="-I$sim_ac_openal_path/include"
+    CPPFLAGS="$CPPFLAGS $sim_ac_openal_cppflags"
+    sim_ac_openal_ldflags="-L$sim_ac_openal_path/lib"
+    LDFLAGS="$LDFLAGS $sim_ac_openal_ldflags"
+    sim_ac_openal_libs="-l$sim_ac_openal_name"
+#    sim_ac_openal_libs="-l$sim_ac_openal_name -alut"
+    # unset sim_ac_openal_candidate
+    # unset sim_ac_openal_path
+  fi
+  LIBS="$sim_ac_openal_libs $LIBS"
+  cat >conftest.$ac_ext <<_ACEOF
+#line $LINENO "configure"
+#include "confdefs.h"
+#include <AL/al.h>
+#ifdef F77_DUMMY_MAIN
+#  ifdef __cplusplus
+     extern "C"
+#  endif
+   int F77_DUMMY_MAIN() { return 1; }
+#endif
+int
+main ()
+{
+(void)alGetError();
+  ;
+  return 0;
+}
+_ACEOF
+rm -f conftest.$ac_objext conftest$ac_exeext
+if { (eval echo "$as_me:$LINENO: \"$ac_link\"") >&5
+  (eval $ac_link) 2>&5
+  ac_status=$?
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); } &&
+         { ac_try='test -s conftest$ac_exeext'
+  { (eval echo "$as_me:$LINENO: \"$ac_try\"") >&5
+  (eval $ac_try) 2>&5
+  ac_status=$?
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); }; }; then
+  sim_ac_have_openal=true
+else
+  echo "$as_me: failed program was:" >&5
+cat conftest.$ac_ext >&5
+fi
+rm -f conftest.$ac_objext conftest$ac_exeext conftest.$ac_ext
+  CPPFLAGS=$sim_ac_openal_save_CPPFLAGS
+  LDFLAGS=$sim_ac_openal_save_LDFLAGS
+  LIBS=$sim_ac_openal_save_LIBS
+  # unset sim_ac_openal_debug
+  # unset sim_ac_openal_name
+  # unset sim_ac_openal_save_CPPFLAGS
+  # unset sim_ac_openal_save_LDFLAGS
+  # unset sim_ac_openal_save_LIBS
+  ;;
+esac
+if $sim_ac_want_openal; then
+  if $sim_ac_have_openal; then
+    echo "$as_me:$LINENO: result: success ($sim_ac_openal_libs)" >&5
+echo "${ECHO_T}success ($sim_ac_openal_libs)" >&6
+
+  CPPFLAGS="$CPPFLAGS $sim_ac_openal_cppflags"
+  LDFLAGS="$LDFLAGS $sim_ac_openal_ldflags"
+  LIBS="$sim_ac_openal_libs $LIBS"
+
+cat >>confdefs.h <<\_ACEOF
+#define HAVE_OPENAL 1
+_ACEOF
+
+  if test x${sim_ac_configuration_settings+set} != xset; then
+  sim_ac_configuration_settings="OpenAL support:Yes, link-time binding"
+else
+  sim_ac_configuration_settings="$sim_ac_configuration_settings|OpenAL support:Yes, link-time binding"
+fi
+
+
+  else
+    echo "$as_me:$LINENO: result: failure" >&5
+echo "${ECHO_T}failure" >&6
+
+  if $sim_ac_enable_sound; then
+    { echo "$as_me:$LINENO: WARNING: openal is needed for sound" >&5
+echo "$as_me: WARNING: openal is needed for sound" >&2;}
+    sim_ac_enable_sound=false
+  fi
+  if test x${sim_ac_configuration_settings+set} != xset; then
+  sim_ac_configuration_settings="OpenAL support:No"
+else
+  sim_ac_configuration_settings="$sim_ac_configuration_settings|OpenAL support:No"
+fi
+
+
+  fi
+else
+  echo "$as_me:$LINENO: result: disabled" >&5
+echo "${ECHO_T}disabled" >&6
+
+  if $sim_ac_enable_sound; then
+    { echo "$as_me:$LINENO: WARNING: openal is needed for sound" >&5
+echo "$as_me: WARNING: openal is needed for sound" >&2;}
+    sim_ac_enable_sound=false
+  fi
+  if test x${sim_ac_configuration_settings+set} != xset; then
+  sim_ac_configuration_settings="OpenAL support:No"
+else
+  sim_ac_configuration_settings="$sim_ac_configuration_settings|OpenAL support:No"
+fi
+
+
+fi
+# unset sim_ac_want_openal
+
+fi
+
+HAVE_SOUND=1
+
+if $sim_ac_enable_sound ; then
+
+cat >>confdefs.h <<\_ACEOF
+#define HAVE_SOUND
+_ACEOF
+
+  if test x${sim_ac_configuration_settings+set} != xset; then
+  sim_ac_configuration_settings="Sound support:Yes"
+else
+  sim_ac_configuration_settings="$sim_ac_configuration_settings|Sound support:Yes"
+fi
+
+else
+  HAVE_SOUND=0
+  if test x${sim_ac_configuration_settings+set} != xset; then
+  sim_ac_configuration_settings="Sound support:No  (enable with --enable-sound)"
+else
+  sim_ac_configuration_settings="$sim_ac_configuration_settings|Sound support:No  (enable with --enable-sound)"
+fi
+
+fi
+
+
+
+
+if $sim_ac_enable_sound; then
+  BUILD_WITH_SOUND_TRUE=
+  BUILD_WITH_SOUND_FALSE='#'
+else
+  BUILD_WITH_SOUND_TRUE='#'
+  BUILD_WITH_SOUND_FALSE=
+fi
+
+
 
 # *******************************************************************
 # * Mathlib stuff.
@@ -21147,9 +21180,6 @@ s,@BUILD_3DS_CAPABILITIES_FALSE@,$BUILD_3DS_CAPABILITIES_FALSE,;t t
 s,@HAVE_VRML97@,$HAVE_VRML97,;t t
 s,@BUILD_VRML97_TRUE@,$BUILD_VRML97_TRUE,;t t
 s,@BUILD_VRML97_FALSE@,$BUILD_VRML97_FALSE,;t t
-s,@HAVE_SOUND@,$HAVE_SOUND,;t t
-s,@BUILD_WITH_SOUND_TRUE@,$BUILD_WITH_SOUND_TRUE,;t t
-s,@BUILD_WITH_SOUND_FALSE@,$BUILD_WITH_SOUND_FALSE,;t t
 s,@subdirs@,$subdirs,;t t
 s,@HAVE_SUPERGLU@,$HAVE_SUPERGLU,;t t
 s,@SUPERGLUPREFIX@,$SUPERGLUPREFIX,;t t
@@ -21177,6 +21207,9 @@ s,@CONFIG@,$CONFIG,;t t
 s,@SUFFIX@,$SUFFIX,;t t
 s,@DSUFFIX@,$DSUFFIX,;t t
 s,@sim_ac_simage_configcmd@,$sim_ac_simage_configcmd,;t t
+s,@HAVE_SOUND@,$HAVE_SOUND,;t t
+s,@BUILD_WITH_SOUND_TRUE@,$BUILD_WITH_SOUND_TRUE,;t t
+s,@BUILD_WITH_SOUND_FALSE@,$BUILD_WITH_SOUND_FALSE,;t t
 s,@X_CFLAGS@,$X_CFLAGS,;t t
 s,@X_PRE_LIBS@,$X_PRE_LIBS,;t t
 s,@X_LIBS@,$X_LIBS,;t t
