Bootstrap.

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -31390,6 +31390,66 @@ fi
 fi
 
 
+
+  echo "$as_me:$LINENO: checking whether we can use AGL pBuffers" >&5
+echo $ECHO_N "checking whether we can use AGL pBuffers... $ECHO_C" >&6
+if test "${sim_cv_agl_pbuffer_avail+set}" = set; then
+  echo $ECHO_N "(cached) $ECHO_C" >&6
+else
+  cat >conftest.$ac_ext <<_ACEOF
+#line $LINENO "configure"
+/* confdefs.h.  */
+_ACEOF
+cat confdefs.h >>conftest.$ac_ext
+cat >>conftest.$ac_ext <<_ACEOF
+/* end confdefs.h.  */
+ #include <AGL/agl.h>
+int
+main ()
+{
+AGLPbuffer pbuffer;
+  ;
+  return 0;
+}
+_ACEOF
+rm -f conftest.$ac_objext conftest$ac_exeext
+if { (eval echo "$as_me:$LINENO: \"$ac_link\"") >&5
+  (eval $ac_link) 2>&5
+  ac_status=$?
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); } &&
+         { ac_try='test -s conftest$ac_exeext'
+  { (eval echo "$as_me:$LINENO: \"$ac_try\"") >&5
+  (eval $ac_try) 2>&5
+  ac_status=$?
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); }; }; then
+  sim_cv_agl_pbuffer_avail=yes
+else
+  echo "$as_me: failed program was:" >&5
+sed 's/^/| /' conftest.$ac_ext >&5
+
+sim_cv_agl_pbuffer_avail=no
+fi
+rm -f conftest.$ac_objext conftest$ac_exeext conftest.$ac_ext
+fi
+echo "$as_me:$LINENO: result: $sim_cv_agl_pbuffer_avail" >&5
+echo "${ECHO_T}$sim_cv_agl_pbuffer_avail" >&6
+
+  if test x"$sim_cv_agl_pbuffer_avail" = xyes; then
+
+
+cat >>confdefs.h <<_ACEOF
+#define HAVE_AGL_PBUFFER 1
+_ACEOF
+
+
+  else
+    :
+  fi
+
+
+
   if $enable_superglu; then
 
 if test x"${sim_ac_configuration_settings+set}" = x"set"; then
