Add user32.lib, to get at Win32 API MessageBox(). Bootstrap.

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -15440,6 +15440,68 @@ cat >>confdefs.h <<\_ACEOF
 #define HAVE_TIMEGETTIME
 _ACEOF
 
+  COIN_EXTRA_LIBS="$COIN_EXTRA_LIBS -lwinmm"
+
+else
+  echo "$as_me: failed program was:" >&5
+cat conftest.$ac_ext >&5
+
+  echo "$as_me:$LINENO: result: no" >&5
+echo "${ECHO_T}no" >&6
+  LIBS=$sim_ac_save_LIBS
+
+fi
+rm -f conftest.$ac_objext conftest$ac_exeext conftest.$ac_ext
+
+# *******************************************************************
+# The MessageBox() Win32 API call is used in SoDB.cpp to throw up
+# an error message when multiple Coin-instances are detected in the
+# same process image.
+
+sim_ac_save_LIBS=$LIBS
+LIBS="$LIBS -luser32"
+echo "$as_me:$LINENO: checking for MessageBox() function" >&5
+echo $ECHO_N "checking for MessageBox() function... $ECHO_C" >&6
+cat >conftest.$ac_ext <<_ACEOF
+#line $LINENO "configure"
+#include "confdefs.h"
+
+#ifdef HAVE_WINDOWS_H
+#include <windows.h>
+#endif
+
+#ifdef F77_DUMMY_MAIN
+#  ifdef __cplusplus
+     extern "C"
+#  endif
+   int F77_DUMMY_MAIN() { return 1; }
+#endif
+int
+main ()
+{
+
+  (void)MessageBox(NULL, NULL, NULL, 0);
+
+  ;
+  return 0;
+}
+_ACEOF
+rm -f conftest.$ac_objext conftest$ac_exeext
+if { (eval echo "$as_me:$LINENO: \"$ac_link\"") >&5
+  (eval $ac_link) 2>&5
+  ac_status=$?
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); } &&
+         { ac_try='test -s conftest$ac_exeext'
+  { (eval echo "$as_me:$LINENO: \"$ac_try\"") >&5
+  (eval $ac_try) 2>&5
+  ac_status=$?
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); }; }; then
+
+  echo "$as_me:$LINENO: result: yes" >&5
+echo "${ECHO_T}yes" >&6
+  COIN_EXTRA_LIBS="$COIN_EXTRA_LIBS -luser32"
 
 else
   echo "$as_me: failed program was:" >&5
