Remove unnecessary and buggy duplisation of code in configure.in. Problem reported by Sven-K?re Evenseth.
Factorized WGL detection code.

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -1,5 +1,5 @@
 #! /bin/sh
-# From configure.in Revision: 1.166 .
+# From configure.in Revision: 1.167 .
 # Guess values for system-dependent variables and create Makefiles.
 # Generated by Autoconf 2.50 for Coin 0.9.99.
 #
@@ -9887,68 +9887,80 @@ if test x"$sim_ac_gl_avail" = xyes; then
   # ** Check what OpenGL->windowsystem bindings are available.
   # *******************************************************************
 
-  echo "$as_me:9890: checking whether GLX is available" >&5
-echo $ECHO_N "checking whether GLX is available... $ECHO_C" >&6
-if test "${sim_cv_func_glx_avail+set}" = set; then
+echo "$as_me:9890: checking whether GLX is on the system" >&5
+echo $ECHO_N "checking whether GLX is on the system... $ECHO_C" >&6
+if test "${sim_cv_have_glx+set}" = set; then
   echo $ECHO_N "(cached) $ECHO_C" >&6
 else
   cat >conftest.$ac_ext <<_ACEOF
 #line 9896 "configure"
 #include "confdefs.h"
+
 #include <GL/glx.h>
+#include <GL/gl.h>
+
 int
 main ()
 {
+
 (void)glXChooseVisual(0L, 0, 0L);
+/* Defect JAGad01283 of HP's aCC compiler causes a link failure unless
+   there is at least one "pure" OpenGL call along with GLU calls. */
+glEnd();
+
   ;
   return 0;
 }
 _ACEOF
 rm -f conftest.$ac_objext conftest$ac_exeext
-if { (eval echo "$as_me:9908: \"$ac_link\"") >&5
+if { (eval echo "$as_me:9916: \"$ac_link\"") >&5
   (eval $ac_link) 2>&5
   ac_status=$?
-  echo "$as_me:9911: \$? = $ac_status" >&5
+  echo "$as_me:9919: \$? = $ac_status" >&5
   (exit $ac_status); } &&
          { ac_try='test -s conftest$ac_exeext'
-  { (eval echo "$as_me:9914: \"$ac_try\"") >&5
+  { (eval echo "$as_me:9922: \"$ac_try\"") >&5
   (eval $ac_try) 2>&5
   ac_status=$?
-  echo "$as_me:9917: \$? = $ac_status" >&5
+  echo "$as_me:9925: \$? = $ac_status" >&5
   (exit $ac_status); }; }; then
-  sim_cv_func_glx_avail=yes
+  sim_cv_have_glx=true
 else
   echo "$as_me: failed program was:" >&5
 cat conftest.$ac_ext >&5
-sim_cv_func_glx_avail=no
+sim_cv_have_glx=false
 fi
 rm -f conftest.$ac_objext conftest$ac_exeext conftest.$ac_ext
 fi
-echo "$as_me:9927: result: $sim_cv_func_glx_avail" >&5
-echo "${ECHO_T}$sim_cv_func_glx_avail" >&6
+echo "$as_me:9935: result: $sim_cv_have_glx" >&5
+echo "${ECHO_T}$sim_cv_have_glx" >&6
 
-  if test x"$sim_cv_func_glx_avail" = xyes; then
+if ${sim_cv_have_glx=false}; then
 
 cat >>confdefs.h <<\EOF
 #define HAVE_GLX
 EOF
 
-  fi
+else
+  :
+fi
 
-  # Try to link against wgl*() calls.
-  sim_ac_save_libs=$LIBS
-  # Not directly needed by the wgl*() calls, but to create a
-  # context we need functions from this library.
-  LIBS="$LIBS -lgdi32"
-  echo "$as_me:9943: checking whether WGL is available" >&5
-echo $ECHO_N "checking whether WGL is available... $ECHO_C" >&6
-if test "${sim_cv_func_wgl_avail+set}" = set; then
+sim_ac_save_libs=$LIBS
+sim_ac_wgl_libs="-lgdi32"
+LIBS="$LIBS $sim_ac_wgl_libs"
+
+echo "$as_me:9952: checking whether WGL is on the system" >&5
+echo $ECHO_N "checking whether WGL is on the system... $ECHO_C" >&6
+if test "${sim_cv_have_wgl+set}" = set; then
   echo $ECHO_N "(cached) $ECHO_C" >&6
 else
   cat >conftest.$ac_ext <<_ACEOF
-#line 9949 "configure"
+#line 9958 "configure"
 #include "confdefs.h"
+
 #include <windows.h>
+#include <GL/gl.h>
+
 int
 main ()
 {
@@ -9958,38 +9970,41 @@ main ()
 }
 _ACEOF
 rm -f conftest.$ac_objext conftest$ac_exeext
-if { (eval echo "$as_me:9961: \"$ac_link\"") >&5
+if { (eval echo "$as_me:9973: \"$ac_link\"") >&5
   (eval $ac_link) 2>&5
   ac_status=$?
-  echo "$as_me:9964: \$? = $ac_status" >&5
+  echo "$as_me:9976: \$? = $ac_status" >&5
   (exit $ac_status); } &&
          { ac_try='test -s conftest$ac_exeext'
-  { (eval echo "$as_me:9967: \"$ac_try\"") >&5
+  { (eval echo "$as_me:9979: \"$ac_try\"") >&5
   (eval $ac_try) 2>&5
   ac_status=$?
-  echo "$as_me:9970: \$? = $ac_status" >&5
+  echo "$as_me:9982: \$? = $ac_status" >&5
   (exit $ac_status); }; }; then
-  sim_cv_func_wgl_avail=yes
+  sim_cv_have_wgl=true
 else
   echo "$as_me: failed program was:" >&5
 cat conftest.$ac_ext >&5
-sim_cv_func_wgl_avail=no
+sim_cv_have_wgl=false
 fi
 rm -f conftest.$ac_objext conftest$ac_exeext conftest.$ac_ext
 fi
-echo "$as_me:9980: result: $sim_cv_func_wgl_avail" >&5
-echo "${ECHO_T}$sim_cv_func_wgl_avail" >&6
+echo "$as_me:9992: result: $sim_cv_have_wgl" >&5
+echo "${ECHO_T}$sim_cv_have_wgl" >&6
 
-  if test x"$sim_cv_func_wgl_avail" = xyes; then
+LIBS=$sim_ac_save_libs
+if ${sim_cv_have_wgl=false}; then
 
 cat >>confdefs.h <<\EOF
 #define HAVE_WGL
 EOF
 
-    COIN_EXTRA_LIBS="$COIN_EXTRA_LIBS -lgdi32"
-  else
-    LIBS=$sim_ac_save_libs
-  fi
+    LIBS="$LIBS $sim_ac_wgl_libs"
+    COIN_EXTRA_LIBS="$COIN_EXTRA_LIBS $sim_ac_wgl_libs"
+
+else
+  :
+fi
 
   # *******************************************************************
   # ** Check if GLU should be loaded and linked at runtime (to avoid
@@ -10001,7 +10016,7 @@ if test "${enable_dl_glu+set}" = set; then
   case "${enableval}" in
       yes | true) enable_dl_glu=true ;;
       no | false) enable_dl_glu=false ;;
-      *) { { echo "$as_me:10004: error: bad value \"${enableval}\" for --enable-dl-glu" >&5
+      *) { { echo "$as_me:10019: error: bad value \"${enableval}\" for --enable-dl-glu" >&5
 echo "$as_me: error: bad value \"${enableval}\" for --enable-dl-glu" >&2;}
    { (exit 1); exit 1; }; } ;;
     esac
@@ -10012,13 +10027,13 @@ fi;
   if $coin_can_do_runtime_linking && $enable_dl_glu; then
     # See if GLU is part of GL library (this is the case on BeOS, for
     # instance) before setting us up for runtime linking.
-    echo "$as_me:10015: checking if GLU is available as part of GL library" >&5
+    echo "$as_me:10030: checking if GLU is available as part of GL library" >&5
 echo $ECHO_N "checking if GLU is available as part of GL library... $ECHO_C" >&6
 if test "${sim_cv_glu_ready+set}" = set; then
   echo $ECHO_N "(cached) $ECHO_C" >&6
 else
   cat >conftest.$ac_ext <<_ACEOF
-#line 10021 "configure"
+#line 10036 "configure"
 #include "confdefs.h"
 
 #if HAVE_WINDOWS_H
@@ -10041,16 +10056,16 @@ glEnd();
 }
 _ACEOF
 rm -f conftest.$ac_objext conftest$ac_exeext
-if { (eval echo "$as_me:10044: \"$ac_link\"") >&5
+if { (eval echo "$as_me:10059: \"$ac_link\"") >&5
   (eval $ac_link) 2>&5
   ac_status=$?
-  echo "$as_me:10047: \$? = $ac_status" >&5
+  echo "$as_me:10062: \$? = $ac_status" >&5
   (exit $ac_status); } &&
          { ac_try='test -s conftest$ac_exeext'
-  { (eval echo "$as_me:10050: \"$ac_try\"") >&5
+  { (eval echo "$as_me:10065: \"$ac_try\"") >&5
   (eval $ac_try) 2>&5
   ac_status=$?
-  echo "$as_me:10053: \$? = $ac_status" >&5
+  echo "$as_me:10068: \$? = $ac_status" >&5
   (exit $ac_status); }; }; then
   sim_cv_glu_ready=true
 else
@@ -10060,7 +10075,7 @@ sim_cv_glu_ready=false
 fi
 rm -f conftest.$ac_objext conftest$ac_exeext conftest.$ac_ext
 fi
-echo "$as_me:10063: result: $sim_cv_glu_ready" >&5
+echo "$as_me:10078: result: $sim_cv_glu_ready" >&5
 echo "${ECHO_T}$sim_cv_glu_ready" >&6
 if ${sim_cv_glu_ready}; then
 
@@ -10132,7 +10147,7 @@ if test x"$with_glu" != xno; then
   CPPFLAGS="$CPPFLAGS $sim_ac_glu_cppflags"
   LDFLAGS="$LDFLAGS $sim_ac_glu_ldflags"
 
-  echo "$as_me:10135: checking whether GLU is available" >&5
+  echo "$as_me:10150: checking whether GLU is available" >&5
 echo $ECHO_N "checking whether GLU is available... $ECHO_C" >&6
 if test "${sim_cv_lib_glu+set}" = set; then
   echo $ECHO_N "(cached) $ECHO_C" >&6
@@ -10145,7 +10160,7 @@ else
       if test "x$sim_cv_lib_glu" = "xUNRESOLVED"; then
         LIBS="$sim_ac_glu_libcheck $sim_ac_save_libs"
         cat >conftest.$ac_ext <<_ACEOF
-#line 10148 "configure"
+#line 10163 "configure"
 #include "confdefs.h"
 
 #if HAVE_WINDOWS_H
@@ -10168,16 +10183,16 @@ glEnd();
 }
 _ACEOF
 rm -f conftest.$ac_objext conftest$ac_exeext
-if { (eval echo "$as_me:10171: \"$ac_link\"") >&5
+if { (eval echo "$as_me:10186: \"$ac_link\"") >&5
   (eval $ac_link) 2>&5
   ac_status=$?
-  echo "$as_me:10174: \$? = $ac_status" >&5
+  echo "$as_me:10189: \$? = $ac_status" >&5
   (exit $ac_status); } &&
          { ac_try='test -s conftest$ac_exeext'
-  { (eval echo "$as_me:10177: \"$ac_try\"") >&5
+  { (eval echo "$as_me:10192: \"$ac_try\"") >&5
   (eval $ac_try) 2>&5
   ac_status=$?
-  echo "$as_me:10180: \$? = $ac_status" >&5
+  echo "$as_me:10195: \$? = $ac_status" >&5
   (exit $ac_status); }; }; then
   sim_cv_lib_glu="$sim_ac_glu_libcheck"
 else
@@ -10189,7 +10204,7 @@ rm -f conftest.$ac_objext conftest$ac_exeext conftest.$ac_ext
     done
 
 fi
-echo "$as_me:10192: result: $sim_cv_lib_glu" >&5
+echo "$as_me:10207: result: $sim_cv_lib_glu" >&5
 echo "${ECHO_T}$sim_cv_lib_glu" >&6
 
   LIBS="$sim_ac_save_libs"
@@ -10236,11 +10251,11 @@ else # couldn't link with OpenGL
     # FIXME: should be able to handle systems where OpenGL is not available,
     # as it would be handy for making e.g. import/export-only versions of the
     # library. 20000123 mortene.
-    { { echo "$as_me:10239: error: needs an OpenGL-compatible development system installed to compile Coin" >&5
+    { { echo "$as_me:10254: error: needs an OpenGL-compatible development system installed to compile Coin" >&5
 echo "$as_me: error: needs an OpenGL-compatible development system installed to compile Coin" >&2;}
    { (exit 1); exit 1; }; }
   else
-    { echo "$as_me:10243: WARNING: needs an OpenGL-compatible development system installed to compile Coin" >&5
+    { echo "$as_me:10258: WARNING: needs an OpenGL-compatible development system installed to compile Coin" >&5
 echo "$as_me: WARNING: needs an OpenGL-compatible development system installed to compile Coin" >&2;}
   fi
 
@@ -10259,7 +10274,7 @@ if test "${enable_compact+set}" = set; then
   case "${enableval}" in
     yes | true)  enable_compact=yes ;;
     no | false)  enable_compact=no ;;
-    *) { { echo "$as_me:10262: error: bad value \"${enableval}\" for --enable-compact" >&5
+    *) { { echo "$as_me:10277: error: bad value \"${enableval}\" for --enable-compact" >&5
 echo "$as_me: error: bad value \"${enableval}\" for --enable-compact" >&2;}
    { (exit 1); exit 1; }; } ;;
   esac
@@ -10286,7 +10301,7 @@ if test "${enable_hacking+set}" = set; then
   case "${enableval}" in
     yes | true)  enable_hacking=yes ;;
     no | false)  enable_hacking=no ;;
-    *) { { echo "$as_me:10289: error: bad value \"${enableval}\" for --enable-hacking" >&5
+    *) { { echo "$as_me:10304: error: bad value \"${enableval}\" for --enable-hacking" >&5
 echo "$as_me: error: bad value \"${enableval}\" for --enable-hacking" >&2;}
    { (exit 1); exit 1; }; } ;;
   esac
@@ -10688,7 +10703,7 @@ DEFS=-DHAVE_CONFIG_H
 : ${CONFIG_STATUS=./config.status}
 ac_clean_files_save=$ac_clean_files
 ac_clean_files="$ac_clean_files $CONFIG_STATUS"
-{ echo "$as_me:10691: creating $CONFIG_STATUS" >&5
+{ echo "$as_me:10706: creating $CONFIG_STATUS" >&5
 echo "$as_me: creating $CONFIG_STATUS" >&6;}
 cat >$CONFIG_STATUS <<_ACEOF
 #! $SHELL
@@ -10864,7 +10879,7 @@ cat >>$CONFIG_STATUS <<\EOF
     echo "$ac_cs_version"; exit 0 ;;
   --he | --h)
     # Conflict between --help and --header
-    { { echo "$as_me:10867: error: ambiguous option: $1
+    { { echo "$as_me:10882: error: ambiguous option: $1
 Try \`$0 --help' for more information." >&5
 echo "$as_me: error: ambiguous option: $1
 Try \`$0 --help' for more information." >&2;}
@@ -10920,12 +10935,12 @@ Try \`$0 --help' for more information." >&2;}
   'include/Inventor/system/inttypes.h' ) CONFIG_HEADERS="$CONFIG_HEADERS include/Inventor/system/inttypes.h" ;;
 
   # This is an error.
-  -*) { { echo "$as_me:10923: error: unrecognized option: $1
+  -*) { { echo "$as_me:10938: error: unrecognized option: $1
 Try \`$0 --help' for more information." >&5
 echo "$as_me: error: unrecognized option: $1
 Try \`$0 --help' for more information." >&2;}
    { (exit 1); exit 1; }; } ;;
-  *) { { echo "$as_me:10928: error: invalid argument: $1" >&5
+  *) { { echo "$as_me:10943: error: invalid argument: $1" >&5
 echo "$as_me: error: invalid argument: $1" >&2;}
    { (exit 1); exit 1; }; };;
   esac
@@ -11246,7 +11261,7 @@ done; }
   esac
 
   if test x"$ac_file" != x-; then
-    { echo "$as_me:11249: creating $ac_file" >&5
+    { echo "$as_me:11264: creating $ac_file" >&5
 echo "$as_me: creating $ac_file" >&6;}
     rm -f "$ac_file"
   fi
@@ -11264,7 +11279,7 @@ echo "$as_me: creating $ac_file" >&6;}
       -) echo $tmp/stdin ;;
       [\\/$]*)
          # Absolute (can't be DOS-style, as IFS=:)
-         test -f "$f" || { { echo "$as_me:11267: error: cannot find input file: $f" >&5
+         test -f "$f" || { { echo "$as_me:11282: error: cannot find input file: $f" >&5
 echo "$as_me: error: cannot find input file: $f" >&2;}
    { (exit 1); exit 1; }; }
          echo $f;;
@@ -11277,7 +11292,7 @@ echo "$as_me: error: cannot find input file: $f" >&2;}
            echo $srcdir/$f
          else
            # /dev/null tree
-           { { echo "$as_me:11280: error: cannot find input file: $f" >&5
+           { { echo "$as_me:11295: error: cannot find input file: $f" >&5
 echo "$as_me: error: cannot find input file: $f" >&2;}
    { (exit 1); exit 1; }; }
          fi;;
@@ -11338,7 +11353,7 @@ for ac_file in : $CONFIG_HEADERS; do test "x$ac_file" = x: && continue
   * )   ac_file_in=$ac_file.in ;;
   esac
 
-  test x"$ac_file" != x- && { echo "$as_me:11341: creating $ac_file" >&5
+  test x"$ac_file" != x- && { echo "$as_me:11356: creating $ac_file" >&5
 echo "$as_me: creating $ac_file" >&6;}
 
   # First look for the input files in the build tree, otherwise in the
@@ -11349,7 +11364,7 @@ echo "$as_me: creating $ac_file" >&6;}
       -) echo $tmp/stdin ;;
       [\\/$]*)
          # Absolute (can't be DOS-style, as IFS=:)
-         test -f "$f" || { { echo "$as_me:11352: error: cannot find input file: $f" >&5
+         test -f "$f" || { { echo "$as_me:11367: error: cannot find input file: $f" >&5
 echo "$as_me: error: cannot find input file: $f" >&2;}
    { (exit 1); exit 1; }; }
          echo $f;;
@@ -11362,7 +11377,7 @@ echo "$as_me: error: cannot find input file: $f" >&2;}
            echo $srcdir/$f
          else
            # /dev/null tree
-           { { echo "$as_me:11365: error: cannot find input file: $f" >&5
+           { { echo "$as_me:11380: error: cannot find input file: $f" >&5
 echo "$as_me: error: cannot find input file: $f" >&2;}
    { (exit 1); exit 1; }; }
          fi;;
@@ -11479,7 +11494,7 @@ cat >>$CONFIG_STATUS <<\EOF
   rm -f $tmp/in
   if test x"$ac_file" != x-; then
     if cmp -s $ac_file $tmp/config.h 2>/dev/null; then
-      { echo "$as_me:11482: $ac_file is unchanged" >&5
+      { echo "$as_me:11497: $ac_file is unchanged" >&5
 echo "$as_me: $ac_file is unchanged" >&6;}
     else
       ac_dir=`$as_expr X"$ac_file" : 'X\(.*[^/]\)//*[^/][^/]*/*$' \| \
