Cygwin issues: - Install wrapmsvc.exe. - Use the installed compiler from coin-config so the source hierarchy can   be removed after the build.

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -1,5 +1,5 @@
 #! /bin/sh
-# From configure.in Revision: 1.182 .
+# From configure.in Revision: 1.183 .
 # Guess values for system-dependent variables and create Makefiles.
 # Generated by Autoconf 2.52b for Coin 0.9.99.
 #
@@ -11595,6 +11595,14 @@ fi
   eval "coin_configure_date=\"`date +%Y%m%d`\""
 
   fi
+
+  COIN_COMPILER="$CXX"
+  if $BUILD_WITH_MSVC; then
+    # we'll use the installed wrapper when we use the coin-config script later
+    # so we can remove the source code hierarchy
+    COIN_COMPILER="wrapmsvc"
+  fi
+
 else
   if test x${sim_ac_configuration_settings+set} != xset; then
   sim_ac_configuration_settings="Coin build type:build disabled"
@@ -11691,7 +11699,7 @@ DEFS=-DHAVE_CONFIG_H
 : ${CONFIG_STATUS=./config.status}
 ac_clean_files_save=$ac_clean_files
 ac_clean_files="$ac_clean_files $CONFIG_STATUS"
-{ echo "$as_me:11694: creating $CONFIG_STATUS" >&5
+{ echo "$as_me:11702: creating $CONFIG_STATUS" >&5
 echo "$as_me: creating $CONFIG_STATUS" >&6;}
 cat >$CONFIG_STATUS <<_ACEOF
 #! $SHELL
@@ -11867,7 +11875,7 @@ cat >>$CONFIG_STATUS <<\EOF
     echo "$ac_cs_version"; exit 0 ;;
   --he | --h)
     # Conflict between --help and --header
-    { { echo "$as_me:11870: error: ambiguous option: $1
+    { { echo "$as_me:11878: error: ambiguous option: $1
 Try \`$0 --help' for more information." >&5
 echo "$as_me: error: ambiguous option: $1
 Try \`$0 --help' for more information." >&2;}
@@ -11886,7 +11894,7 @@ Try \`$0 --help' for more information." >&2;}
     ac_need_defaults=false;;
 
   # This is an error.
-  -*) { { echo "$as_me:11889: error: unrecognized option: $1
+  -*) { { echo "$as_me:11897: error: unrecognized option: $1
 Try \`$0 --help' for more information." >&5
 echo "$as_me: error: unrecognized option: $1
 Try \`$0 --help' for more information." >&2;}
@@ -11974,7 +11982,7 @@ do
   "default-1" ) CONFIG_COMMANDS="$CONFIG_COMMANDS default-1" ;;
   "default-2" ) CONFIG_COMMANDS="$CONFIG_COMMANDS default-2" ;;
   "include/config.h" ) CONFIG_HEADERS="$CONFIG_HEADERS include/config.h" ;;
-  *) { { echo "$as_me:11977: error: invalid argument: $ac_config_target" >&5
+  *) { { echo "$as_me:11985: error: invalid argument: $ac_config_target" >&5
 echo "$as_me: error: invalid argument: $ac_config_target" >&2;}
    { (exit 1); exit 1; }; };;
   esac
@@ -12152,6 +12160,7 @@ s,@LIBFLAGS@,$LIBFLAGS,;t t
 s,@BUILD_WITH_MSVC_TRUE@,$BUILD_WITH_MSVC_TRUE,;t t
 s,@BUILD_WITH_MSVC_FALSE@,$BUILD_WITH_MSVC_FALSE,;t t
 s,@coin_configure_date@,$coin_configure_date,;t t
+s,@COIN_COMPILER@,$COIN_COMPILER,;t t
 CEOF
 
 EOF
@@ -12266,7 +12275,7 @@ done; }
   esac
 
   if test x"$ac_file" != x-; then
-    { echo "$as_me:12269: creating $ac_file" >&5
+    { echo "$as_me:12278: creating $ac_file" >&5
 echo "$as_me: creating $ac_file" >&6;}
     rm -f "$ac_file"
   fi
@@ -12284,7 +12293,7 @@ echo "$as_me: creating $ac_file" >&6;}
       -) echo $tmp/stdin ;;
       [\\/$]*)
          # Absolute (can't be DOS-style, as IFS=:)
-         test -f "$f" || { { echo "$as_me:12287: error: cannot find input file: $f" >&5
+         test -f "$f" || { { echo "$as_me:12296: error: cannot find input file: $f" >&5
 echo "$as_me: error: cannot find input file: $f" >&2;}
    { (exit 1); exit 1; }; }
          echo $f;;
@@ -12297,7 +12306,7 @@ echo "$as_me: error: cannot find input file: $f" >&2;}
            echo $srcdir/$f
          else
            # /dev/null tree
-           { { echo "$as_me:12300: error: cannot find input file: $f" >&5
+           { { echo "$as_me:12309: error: cannot find input file: $f" >&5
 echo "$as_me: error: cannot find input file: $f" >&2;}
    { (exit 1); exit 1; }; }
          fi;;
@@ -12358,7 +12367,7 @@ for ac_file in : $CONFIG_HEADERS; do test "x$ac_file" = x: && continue
   * )   ac_file_in=$ac_file.in ;;
   esac
 
-  test x"$ac_file" != x- && { echo "$as_me:12361: creating $ac_file" >&5
+  test x"$ac_file" != x- && { echo "$as_me:12370: creating $ac_file" >&5
 echo "$as_me: creating $ac_file" >&6;}
 
   # First look for the input files in the build tree, otherwise in the
@@ -12369,7 +12378,7 @@ echo "$as_me: creating $ac_file" >&6;}
       -) echo $tmp/stdin ;;
       [\\/$]*)
          # Absolute (can't be DOS-style, as IFS=:)
-         test -f "$f" || { { echo "$as_me:12372: error: cannot find input file: $f" >&5
+         test -f "$f" || { { echo "$as_me:12381: error: cannot find input file: $f" >&5
 echo "$as_me: error: cannot find input file: $f" >&2;}
    { (exit 1); exit 1; }; }
          echo $f;;
@@ -12382,7 +12391,7 @@ echo "$as_me: error: cannot find input file: $f" >&2;}
            echo $srcdir/$f
          else
            # /dev/null tree
-           { { echo "$as_me:12385: error: cannot find input file: $f" >&5
+           { { echo "$as_me:12394: error: cannot find input file: $f" >&5
 echo "$as_me: error: cannot find input file: $f" >&2;}
    { (exit 1); exit 1; }; }
          fi;;
@@ -12499,7 +12508,7 @@ cat >>$CONFIG_STATUS <<\EOF
   rm -f $tmp/in
   if test x"$ac_file" != x-; then
     if cmp -s $ac_file $tmp/config.h 2>/dev/null; then
-      { echo "$as_me:12502: $ac_file is unchanged" >&5
+      { echo "$as_me:12511: $ac_file is unchanged" >&5
 echo "$as_me: $ac_file is unchanged" >&6;}
     else
       ac_dir=`$as_expr X"$ac_file" : 'X\(.*[^/]\)//*[^/][^/]*/*$' \| \
