bootstrap

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -1096,6 +1096,7 @@ Optional Features:
                           [default=--enable-dl-libbzip2]
   --enable-darwin-x11     enable X11 on Darwin
                           [default=--disable-darwin-x11]
+  --enable-agl            enable AGL on Mac OS X [default=--disable-agl]
   --enable-dl-glu         use runtime dynamic linking for GLU if possible
                           [default=yes]
   --enable-compact        enable hack for compact compilation. Has the
@@ -5271,7 +5272,7 @@ ia64-*-hpux*)
   ;;
 *-*-irix6*)
   # Find out which ABI we are using.
-  echo '#line 5274 "configure"' > conftest.$ac_ext
+  echo '#line 5275 "configure"' > conftest.$ac_ext
   if { (eval echo "$as_me:$LINENO: \"$ac_compile\"") >&5
   (eval $ac_compile) 2>&5
   ac_status=$?
@@ -6406,7 +6407,7 @@ fi
 
 
 # Provide some information about the compiler.
-echo "$as_me:6409:" \
+echo "$as_me:6410:" \
      "checking for Fortran 77 compiler version" >&5
 ac_compiler=`set X $ac_compile; echo $2`
 { (eval echo "$as_me:$LINENO: \"$ac_compiler --version </dev/null >&5\"") >&5
@@ -7469,11 +7470,11 @@ else
    -e 's:.*FLAGS}\{0,1\} :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:7472: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:7473: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>conftest.err)
    ac_status=$?
    cat conftest.err >&5
-   echo "$as_me:7476: \$? = $ac_status" >&5
+   echo "$as_me:7477: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s "$ac_outfile"; then
      # The compiler can only warn and ignore the option if not recognized
      # So say no if there are warnings other than the usual output.
@@ -7737,11 +7738,11 @@ else
    -e 's:.*FLAGS}\{0,1\} :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:7740: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:7741: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>conftest.err)
    ac_status=$?
    cat conftest.err >&5
-   echo "$as_me:7744: \$? = $ac_status" >&5
+   echo "$as_me:7745: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s "$ac_outfile"; then
      # The compiler can only warn and ignore the option if not recognized
      # So say no if there are warnings other than the usual output.
@@ -7841,11 +7842,11 @@ else
    -e 's:.*FLAGS}\{0,1\} :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:7844: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:7845: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>out/conftest.err)
    ac_status=$?
    cat out/conftest.err >&5
-   echo "$as_me:7848: \$? = $ac_status" >&5
+   echo "$as_me:7849: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s out/conftest2.$ac_objext
    then
      # The compiler can only warn and ignore the option if not recognized
@@ -10186,7 +10187,7 @@ else
   lt_dlunknown=0; lt_dlno_uscore=1; lt_dlneed_uscore=2
   lt_status=$lt_dlunknown
   cat > conftest.$ac_ext <<EOF
-#line 10189 "configure"
+#line 10190 "configure"
 #include "confdefs.h"
 
 #if HAVE_DLFCN_H
@@ -10286,7 +10287,7 @@ else
   lt_dlunknown=0; lt_dlno_uscore=1; lt_dlneed_uscore=2
   lt_status=$lt_dlunknown
   cat > conftest.$ac_ext <<EOF
-#line 10289 "configure"
+#line 10290 "configure"
 #include "confdefs.h"
 
 #if HAVE_DLFCN_H
@@ -12626,11 +12627,11 @@ else
    -e 's:.*FLAGS}\{0,1\} :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:12629: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:12630: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>conftest.err)
    ac_status=$?
    cat conftest.err >&5
-   echo "$as_me:12633: \$? = $ac_status" >&5
+   echo "$as_me:12634: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s "$ac_outfile"; then
      # The compiler can only warn and ignore the option if not recognized
      # So say no if there are warnings other than the usual output.
@@ -12730,11 +12731,11 @@ else
    -e 's:.*FLAGS}\{0,1\} :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:12733: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:12734: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>out/conftest.err)
    ac_status=$?
    cat out/conftest.err >&5
-   echo "$as_me:12737: \$? = $ac_status" >&5
+   echo "$as_me:12738: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s out/conftest2.$ac_objext
    then
      # The compiler can only warn and ignore the option if not recognized
@@ -14300,11 +14301,11 @@ else
    -e 's:.*FLAGS}\{0,1\} :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:14303: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:14304: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>conftest.err)
    ac_status=$?
    cat conftest.err >&5
-   echo "$as_me:14307: \$? = $ac_status" >&5
+   echo "$as_me:14308: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s "$ac_outfile"; then
      # The compiler can only warn and ignore the option if not recognized
      # So say no if there are warnings other than the usual output.
@@ -14404,11 +14405,11 @@ else
    -e 's:.*FLAGS}\{0,1\} :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:14407: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:14408: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>out/conftest.err)
    ac_status=$?
    cat out/conftest.err >&5
-   echo "$as_me:14411: \$? = $ac_status" >&5
+   echo "$as_me:14412: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s out/conftest2.$ac_objext
    then
      # The compiler can only warn and ignore the option if not recognized
@@ -16607,11 +16608,11 @@ else
    -e 's:.*FLAGS}\{0,1\} :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:16610: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:16611: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>conftest.err)
    ac_status=$?
    cat conftest.err >&5
-   echo "$as_me:16614: \$? = $ac_status" >&5
+   echo "$as_me:16615: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s "$ac_outfile"; then
      # The compiler can only warn and ignore the option if not recognized
      # So say no if there are warnings other than the usual output.
@@ -16875,11 +16876,11 @@ else
    -e 's:.*FLAGS}\{0,1\} :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:16878: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:16879: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>conftest.err)
    ac_status=$?
    cat conftest.err >&5
-   echo "$as_me:16882: \$? = $ac_status" >&5
+   echo "$as_me:16883: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s "$ac_outfile"; then
      # The compiler can only warn and ignore the option if not recognized
      # So say no if there are warnings other than the usual output.
@@ -16979,11 +16980,11 @@ else
    -e 's:.*FLAGS}\{0,1\} :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:16982: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:16983: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>out/conftest.err)
    ac_status=$?
    cat out/conftest.err >&5
-   echo "$as_me:16986: \$? = $ac_status" >&5
+   echo "$as_me:16987: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s out/conftest2.$ac_objext
    then
      # The compiler can only warn and ignore the option if not recognized
@@ -35164,6 +35165,22 @@ fi
 fi
 
       else
+        # Check whether --enable-agl or --disable-agl was given.
+if test "${enable_agl+set}" = set; then
+  enableval="$enable_agl"
+  case "${enableval}" in
+            yes | true) sim_ac_enable_agl=true ;;
+            no | false) sim_ac_enable_agl=false ;;
+            *)
+{ { echo "$as_me:$LINENO: error: invalid value \"${enableval}\" for \"--enable-agl\" configure argument" >&5
+echo "$as_me: error: invalid value \"${enableval}\" for \"--enable-agl\" configure argument" >&2;}
+   { (exit 1); exit 1; }; }
+ ;;
+           esac
+else
+  sim_ac_enable_agl=false
+fi;
+        if $sim_ac_enable_agl; then
 
 sim_ac_save_ldflags=$LDFLAGS
 sim_ac_agl_ldflags="-Wl,-framework,ApplicationServices -Wl,-framework,AGL -Wl,-framework,Carbon"
@@ -35237,11 +35254,11 @@ cat >>confdefs.h <<\_ACEOF
 #define HAVE_AGL 1
 _ACEOF
 
-          LDFLAGS="$LDFLAGS $sim_ac_agl_ldflags"
-          # indirect linking is not supported in static libs
-          if $COIN_STATIC; then
-            COIN_EXTRA_LDFLAGS="$COIN_EXTRA_LDFLAGS $sim_ac_agl_ldflags"
-          fi
+            LDFLAGS="$LDFLAGS $sim_ac_agl_ldflags"
+            # indirect linking is not supported in static libs
+            if $COIN_STATIC; then
+              COIN_EXTRA_LDFLAGS="$COIN_EXTRA_LDFLAGS $sim_ac_agl_ldflags"
+            fi
 
 for ac_header in OpenGL/CGLCurrent.h
 do
@@ -35366,27 +35383,101 @@ echo "${ECHO_T}$sim_cv_agl_pbuffer_avail" >&6
 
   if test x"$sim_cv_agl_pbuffer_avail" = xyes; then
 
-
 cat >>confdefs.h <<_ACEOF
 #define HAVE_AGL_PBUFFER 1
 _ACEOF
-
 
   else
     :
   fi
 
+
 else
+  :
+fi
+
+        fi
+
+sim_ac_save_ldflags=$LDFLAGS
+sim_ac_cgl_ldflags="-Wl,-framework,OpenGL"
+
+LDFLAGS="$LDFLAGS $sim_ac_cgl_ldflags"
+
+echo "$as_me:$LINENO: checking whether CGL is on the system" >&5
+echo $ECHO_N "checking whether CGL is on the system... $ECHO_C" >&6
+if test "${sim_cv_have_cgl+set}" = set; then
+  echo $ECHO_N "(cached) $ECHO_C" >&6
+else
+  cat >conftest.$ac_ext <<_ACEOF
+/* confdefs.h.  */
+_ACEOF
+cat confdefs.h >>conftest.$ac_ext
+cat >>conftest.$ac_ext <<_ACEOF
+/* end confdefs.h.  */
+#include <OpenGL/OpenGL.h>
+int
+main ()
+{
+CGLGetCurrentContext();
+  ;
+  return 0;
+}
+_ACEOF
+rm -f conftest.$ac_objext conftest$ac_exeext
+if { (eval echo "$as_me:$LINENO: \"$ac_link\"") >&5
+  (eval $ac_link) 2>conftest.er1
+  ac_status=$?
+  grep -v '^ *+' conftest.er1 >conftest.err
+  rm -f conftest.er1
+  cat conftest.err >&5
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); } &&
+	 { ac_try='test -z "$ac_cxx_werror_flag"
+			 || test ! -s conftest.err'
+  { (eval echo "$as_me:$LINENO: \"$ac_try\"") >&5
+  (eval $ac_try) 2>&5
+  ac_status=$?
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); }; } &&
+	 { ac_try='test -s conftest$ac_exeext'
+  { (eval echo "$as_me:$LINENO: \"$ac_try\"") >&5
+  (eval $ac_try) 2>&5
+  ac_status=$?
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); }; }; then
+  sim_cv_have_cgl=true
+else
+  echo "$as_me: failed program was:" >&5
+sed 's/^/| /' conftest.$ac_ext >&5
+
+sim_cv_have_cgl=false
+fi
+rm -f conftest.err conftest.$ac_objext \
+      conftest$ac_exeext conftest.$ac_ext
+fi
+echo "$as_me:$LINENO: result: $sim_cv_have_cgl" >&5
+echo "${ECHO_T}$sim_cv_have_cgl" >&6
+
+LDFLAGS=$sim_ac_save_ldflags
+if ${sim_cv_have_cgl=false}; then
+
+cat >>confdefs.h <<\_ACEOF
+#define HAVE_CGL 1
+_ACEOF
+
+else
+  :
+fi
+
+        if test x"$sim_cv_have_cgl" != x"true" && test x"$sim_cv_have_agl" != x"false" ; then
 
 if test x"${sim_ac_configuration_warnings+set}" = x"set"; then
-  sim_ac_configuration_warnings="$sim_ac_configuration_warnings|Could not find or compile or link against AGL. The SoOffscreenRenderer functionality will be disabled. "
+  sim_ac_configuration_warnings="$sim_ac_configuration_warnings|Could not find or compile or link against AGL or CGL. The SoOffscreenRenderer functionality will be disabled."
 else
-  sim_ac_configuration_warnings="Could not find or compile or link against AGL. The SoOffscreenRenderer functionality will be disabled. "
+  sim_ac_configuration_warnings="Could not find or compile or link against AGL or CGL. The SoOffscreenRenderer functionality will be disabled."
 fi
 
-
-fi
-
+        fi
       fi
     ;;
     * )
