bootstrap

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -1077,6 +1077,7 @@ Optional Packages:
   --with-openal=PATH      enable/disable OpenAL support
   --with-freetype=PATH    enable/disable Freetype support
   --with-zlib=PATH        enable/disable zlib support
+  --with-bzip2=PATH       enable/disable bzip2 support
   --with-x                use the X Window System
   --with-mesa             prefer MesaGL (if found) over OpenGL [default=yes]
   --with-opengl=DIR       OpenGL/Mesa installation directory
@@ -4621,7 +4622,7 @@ test "x$enable_libtool_lock" != xno && enable_libtool_lock=yes
 case $host in
 *-*-irix6*)
   # Find out which ABI we are using.
-  echo '#line 4624 "configure"' > conftest.$ac_ext
+  echo '#line 4625 "configure"' > conftest.$ac_ext
   if { (eval echo "$as_me:$LINENO: \"$ac_compile\"") >&5
   (eval $ac_compile) 2>&5
   ac_status=$?
@@ -5157,7 +5158,7 @@ chmod -w .
 save_CFLAGS="$CFLAGS"
 CFLAGS="$CFLAGS -o out/conftest2.$ac_objext"
 compiler_c_o=no
-if { (eval echo configure:5160: \"$ac_compile\") 1>&5; (eval $ac_compile) 2>out/conftest.err; } && test -s out/conftest2.$ac_objext; then
+if { (eval echo configure:5161: \"$ac_compile\") 1>&5; (eval $ac_compile) 2>out/conftest.err; } && test -s out/conftest2.$ac_objext; then
   # The compiler can only warn and ignore the option if not recognized
   # So say no if there are warnings
   if test -s out/conftest.err; then
@@ -6951,7 +6952,7 @@ else
     lt_dlunknown=0; lt_dlno_uscore=1; lt_dlneed_uscore=2
   lt_status=$lt_dlunknown
   cat > conftest.$ac_ext <<EOF
-#line 6954 "configure"
+#line 6955 "configure"
 #include "confdefs.h"
 
 #if HAVE_DLFCN_H
@@ -7049,7 +7050,7 @@ else
     lt_dlunknown=0; lt_dlno_uscore=1; lt_dlneed_uscore=2
   lt_status=$lt_dlunknown
   cat > conftest.$ac_ext <<EOF
-#line 7052 "configure"
+#line 7053 "configure"
 #include "confdefs.h"
 
 #if HAVE_DLFCN_H
@@ -14154,20 +14155,22 @@ if $enable_debug; then
     CPPFLAGS="$CPPFLAGS -fno-builtin";    # no auto string.h-functions
     CXXFLAGS="$CXXFLAGS -fno-for-scope";  # disallow non-standard scoping of for()-variables
     CPPFLAGS="$CPPFLAGS -Wreturn-type";   # warn on missing return-value
-    if test x"a" = x""; then :; else
+    if test x"$COIN_BETA_VERSION" = x""; then :; else
       # don't let people get away with warnings, except for in
-      # source code releases.
+      # official source code releases.
       CPPFLAGS="$CPPFLAGS -Werror";
     fi
-  # FIXME: enable this code after releasing 2.0.0   20030226 larsa
-  # else
-  #   case $CXX in
-  #   *wrapmsvc* )
-  #     if test x"COIN_BETA" = x""; then :; else
-  #       CPPFLAGS="$CPPFLAGS /noBool /W2 /WX"
-  #     fi
-  #     ;;
-  #   esac
+    CPPFLAGS="$CPPFLAGS -Wchar-subscripts";
+    CPPFLAGS="$CPPFLAGS -Wparentheses";
+    CPPFLAGS="$CPPFLAGS -finline-functions";
+  else
+    case $CXX in
+    *wrapmsvc* )
+      if test x"$COIN_BETA_VERSION" = x""; then :; else
+        CPPFLAGS="$CPPFLAGS /noBool /W2 /WX"
+      fi
+      ;;
+    esac
   fi
   CPPFLAGS="$CPPFLAGS -DCOIN_DEBUG=1"
 
@@ -17828,8 +17831,9 @@ fi
 rm -f conftest.$ac_objext conftest$ac_exeext conftest.$ac_ext
 
 # *******************************************************************
-# * Handle the detection and inclusion of zlib
+# * Handle the detection and inclusion of compression libraries
 # *******************************************************************
+
 : ${sim_ac_have_libzlib=false}
 echo "$as_me:$LINENO: checking for zlib" >&5
 echo $ECHO_N "checking for zlib... $ECHO_C" >&6
@@ -17974,6 +17978,152 @@ fi
 
 fi
 # unset sim_ac_want_libzlib
+
+
+: ${sim_ac_have_libbzip2=false}
+echo "$as_me:$LINENO: checking for bzip2 (library)" >&5
+echo $ECHO_N "checking for bzip2 (library)... $ECHO_C" >&6
+
+# Check whether --with-zlib or --without-zlib was given.
+if test "${with_zlib+set}" = set; then
+  withval="$with_zlib"
+  case $withval in
+  yes | "") sim_ac_want_libbzip2=true ;;
+  no)       sim_ac_want_libbzip2=false ;;
+  *)        sim_ac_want_libbzip2=true
+            sim_ac_libbzip2_path=$withval ;;
+  esac
+else
+  sim_ac_want_libbzip2=true
+fi;
+case $sim_ac_want_libbzip2 in
+true)
+  $sim_ac_have_libbzip2 && break
+  sim_ac_libbzip2_save_CPPFLAGS=$CPPFLAGS
+  sim_ac_libbzip2_save_LDFLAGS=$LDFLAGS
+  sim_ac_libbzip2_save_LIBS=$LIBS
+  sim_ac_libbzip2_debug=false
+  test -n "`echo -- $CPPFLAGS $CFLAGS $CXXFLAGS | grep -- '-g\\>'`" &&
+    sim_ac_libbzip2_debug=true
+  # test -z "$sim_ac_libbzip2_path" -a x"$prefix" != xNONE &&
+  #   sim_ac_libbzip2_path=$prefix
+  sim_ac_libbzip2_name=bz2
+  if test -n "$sim_ac_libbzip2_path"; then
+    for sim_ac_libbzip2_candidate in \
+      `( ls $sim_ac_libbzip2_path/lib/bzip2*.lib;
+         ls $sim_ac_libbzip2_path/lib/bzip2*d.lib ) 2>/dev/null`
+    do
+      case $sim_ac_libbzip2_candidate in
+      *d.lib)
+        $sim_ac_libbzip2_debug &&
+          sim_ac_libbzip2_name=`basename $sim_ac_libbzip2_candidate .lib` ;;
+      *.lib)
+        sim_ac_libbzip2_name=`basename $sim_ac_libbzip2_candidate .lib` ;;
+      esac
+    done
+    sim_ac_libbzip2_cppflags="-I$sim_ac_libbzip2_path/include"
+    CPPFLAGS="$CPPFLAGS $sim_ac_libbzip2_cppflags"
+    sim_ac_libbzip2_ldflags="-L$sim_ac_libbzip2_path/lib"
+    LDFLAGS="$LDFLAGS $sim_ac_libbzip2_ldflags"
+    # unset sim_ac_libbzip2_candidate
+    # unset sim_ac_libbzip2_path
+  fi
+  sim_ac_libbzip2_libs="-l$sim_ac_libbzip2_name"
+  LIBS="$sim_ac_libbzip2_libs $LIBS"
+  cat >conftest.$ac_ext <<_ACEOF
+#line $LINENO "configure"
+#include "confdefs.h"
+#include <bzlib.h>
+#ifdef F77_DUMMY_MAIN
+#  ifdef __cplusplus
+     extern "C"
+#  endif
+   int F77_DUMMY_MAIN() { return 1; }
+#endif
+int
+main ()
+{
+(void)BZ2_bzlibVersion();
+  ;
+  return 0;
+}
+_ACEOF
+rm -f conftest.$ac_objext conftest$ac_exeext
+if { (eval echo "$as_me:$LINENO: \"$ac_link\"") >&5
+  (eval $ac_link) 2>&5
+  ac_status=$?
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); } &&
+         { ac_try='test -s conftest$ac_exeext'
+  { (eval echo "$as_me:$LINENO: \"$ac_try\"") >&5
+  (eval $ac_try) 2>&5
+  ac_status=$?
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); }; }; then
+  sim_ac_have_libbzip2=true
+else
+  echo "$as_me: failed program was:" >&5
+cat conftest.$ac_ext >&5
+fi
+rm -f conftest.$ac_objext conftest$ac_exeext conftest.$ac_ext
+  CPPFLAGS=$sim_ac_libbzip2_save_CPPFLAGS
+  LDFLAGS=$sim_ac_libbzip2_save_LDFLAGS
+  LIBS=$sim_ac_libbzip2_save_LIBS
+  # unset sim_ac_libbzip2_debug
+  # unset sim_ac_libbzip2_name
+  # unset sim_ac_libbzip2_save_CPPFLAGS
+  # unset sim_ac_libbzip2_save_LDFLAGS
+  # unset sim_ac_libbzip2_save_LIBS
+  ;;
+esac
+if $sim_ac_want_libbzip2; then
+  if $sim_ac_have_libbzip2; then
+    echo "$as_me:$LINENO: result: success ($sim_ac_libbzip2_libs)" >&5
+echo "${ECHO_T}success ($sim_ac_libbzip2_libs)" >&6
+
+  COIN_EXTRA_CPPFLAGS="$COIN_EXTRA_CPPFLAGS $sim_ac_libbzip2_cppflags"
+  COIN_EXTRA_LDFLAGS="$COIN_EXTRA_LDFLAGS $sim_ac_libbzip2_ldflags"
+  COIN_EXTRA_LIBS="$sim_ac_libbzip2_libs $COIN_EXTRA_LIBS"
+  CPPFLAGS="$CPPFLAGS $sim_ac_libbzip2_cppflags"
+  LDFLAGS="$LDFLAGS $sim_ac_libbzip2_ldflags"
+  LIBS="$sim_ac_libbzip2_libs $LIBS"
+  if test x"${sim_ac_configuration_settings+set}" = x"set"; then
+  sim_ac_configuration_settings="$sim_ac_configuration_settings|bzip2 support:Yes, link-time binding"
+else
+  sim_ac_configuration_settings="bzip2 support:Yes, link-time binding"
+fi
+
+
+cat >>confdefs.h <<\_ACEOF
+#define HAVE_BZIP2 1
+_ACEOF
+
+
+  else
+    echo "$as_me:$LINENO: result: failure" >&5
+echo "${ECHO_T}failure" >&6
+
+  if test x"${sim_ac_configuration_settings+set}" = x"set"; then
+  sim_ac_configuration_settings="$sim_ac_configuration_settings|bzip2 support:No"
+else
+  sim_ac_configuration_settings="bzip2 support:No"
+fi
+
+
+  fi
+else
+  echo "$as_me:$LINENO: result: disabled" >&5
+echo "${ECHO_T}disabled" >&6
+
+  if test x"${sim_ac_configuration_settings+set}" = x"set"; then
+  sim_ac_configuration_settings="$sim_ac_configuration_settings|bzip2 support:No"
+else
+  sim_ac_configuration_settings="bzip2 support:No"
+fi
+
+
+fi
+# unset sim_ac_want_libbzip2
 
 
 # *******************************************************************
