bootstrap

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -36771,8 +36771,25 @@ fi
 
 # **************************************************************************
 
-          ac_config_headers="$ac_config_headers include/config.h"
+                              ac_config_headers="$ac_config_headers include/discard.h include/config.h include/setup.h"
 
+
+sim_ac_tmpfile=/tmp/Coin-2-config-h.$$
+
+sed -e '/^\/\* for setup.h \*\//, /^$/ d' \
+  <$srcdir/include/discard.h.in \
+  >$sim_ac_tmpfile
+
+if cmp -s $sim_ac_tmpfile $srcdir/include/config.h.in; then
+  :
+else
+  rm $sim_ac_tmpfile
+  { { echo "$as_me:$LINENO: error: config.h.in is out of sync - maintainer must update" >&5
+echo "$as_me: error: config.h.in is out of sync - maintainer must update" >&2;}
+   { (exit 1); exit 1; }; }
+fi
+
+rm $sim_ac_tmpfile
 
 # **************************************************************************
 
@@ -37557,7 +37574,9 @@ do
   "src/shaders/Makefile" ) CONFIG_FILES="$CONFIG_FILES src/shaders/Makefile" ;;
   "cfg/gendsp.sh" ) CONFIG_FILES="$CONFIG_FILES cfg/gendsp.sh" ;;
   "depfiles" ) CONFIG_COMMANDS="$CONFIG_COMMANDS depfiles" ;;
+  "include/discard.h" ) CONFIG_HEADERS="$CONFIG_HEADERS include/discard.h" ;;
   "include/config.h" ) CONFIG_HEADERS="$CONFIG_HEADERS include/config.h" ;;
+  "include/setup.h" ) CONFIG_HEADERS="$CONFIG_HEADERS include/setup.h" ;;
   *) { { echo "$as_me:$LINENO: error: invalid argument: $ac_config_target" >&5
 echo "$as_me: error: invalid argument: $ac_config_target" >&2;}
    { (exit 1); exit 1; }; };;
