New bootstrap that disables libtool and unix-like cruft for Cygwin-hosted MSVC++ builds.

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -1,7 +1,7 @@
 #! /bin/sh
 # From configure.in Revision: 1.166 .
 # Guess values for system-dependent variables and create Makefiles.
-# Generated by Autoconf 2.50 for Coin v0.9.99.
+# Generated by Autoconf 2.50 for Coin 0.9.99.
 #
 # Copyright 1992, 1993, 1994, 1995, 1996, 1998, 1999, 2000, 2001
 # Free Software Foundation, Inc.
@@ -145,8 +145,8 @@ mandir='${prefix}/man'
 # Identity of this package.
 PACKAGE_NAME='Coin'
 PACKAGE_TARNAME='coin'
-PACKAGE_VERSION='v0.9.99'
-PACKAGE_STRING='Coin v0.9.99'
+PACKAGE_VERSION='0.9.99'
+PACKAGE_STRING='Coin 0.9.99'
 PACKAGE_BUGREPORT=''
 
 ac_prev=
@@ -566,7 +566,7 @@ if test "$ac_init_help" = "long"; then
   # Omit some internal or obsolete options to make the list less imposing.
   # This message is too long to be a string in the A/UX 3.1 sh.
   cat <<EOF
-\`configure' configures Coin v0.9.99 to adapt to many kinds of systems.
+\`configure' configures Coin 0.9.99 to adapt to many kinds of systems.
 
 Usage: $0 [OPTION]... [VAR=VALUE]...
 
@@ -637,7 +637,7 @@ fi
 
 if test -n "$ac_init_help"; then
   case $ac_init_help in
-     short | recursive ) echo "Configuration of Coin v0.9.99:";;
+     short | recursive ) echo "Configuration of Coin 0.9.99:";;
    esac
   cat <<\EOF
 
@@ -748,7 +748,7 @@ fi
 test -n "$ac_init_help" && exit 0
 if $ac_init_version; then
   cat <<\EOF
-Coin configure v0.9.99
+Coin configure 0.9.99
 generated by GNU Autoconf 2.50
 
 Copyright 1992, 1993, 1994, 1995, 1996, 1998, 1999, 2000, 2001
@@ -763,7 +763,7 @@ cat >&5 <<EOF
 This file contains any messages produced by compilers while
 running configure, to aid debugging if configure makes a mistake.
 
-It was created by Coin $as_me v0.9.99, which was
+It was created by Coin $as_me 0.9.99, which was
 generated by GNU Autoconf 2.50.  Invocation command line was
 
   $ $0 $@
@@ -10506,6 +10506,14 @@ LIBFLAGS=
 # **************************************************************************
 # Remaining setup based on platform.
 
+if $BUILD_WITH_MSVC; then
+  BUILD_WITH_MSVC_TRUE=
+  BUILD_WITH_MSVC_FALSE='#'
+else
+  BUILD_WITH_MSVC_TRUE='#'
+  BUILD_WITH_MSVC_FALSE=
+fi
+
 if $sim_ac_build_library; then
 if $BUILD_WITH_MSVC; then
   if $COIN_STATIC; then
@@ -10680,7 +10688,7 @@ DEFS=-DHAVE_CONFIG_H
 : ${CONFIG_STATUS=./config.status}
 ac_clean_files_save=$ac_clean_files
 ac_clean_files="$ac_clean_files $CONFIG_STATUS"
-{ echo "$as_me:10683: creating $CONFIG_STATUS" >&5
+{ echo "$as_me:10691: creating $CONFIG_STATUS" >&5
 echo "$as_me: creating $CONFIG_STATUS" >&6;}
 cat >$CONFIG_STATUS <<_ACEOF
 #! $SHELL
@@ -10811,7 +10819,7 @@ EOF
 
 cat >>$CONFIG_STATUS <<EOF
 ac_cs_version="\\
-Coin config.status v0.9.99
+Coin config.status 0.9.99
 configured by $0, generated by GNU Autoconf 2.50,
   with options \\"`echo "$ac_configure_args" | sed 's/[\\""\`\$]/\\\\&/g'`\\"
 
@@ -10856,7 +10864,7 @@ cat >>$CONFIG_STATUS <<\EOF
     echo "$ac_cs_version"; exit 0 ;;
   --he | --h)
     # Conflict between --help and --header
-    { { echo "$as_me:10859: error: ambiguous option: $1
+    { { echo "$as_me:10867: error: ambiguous option: $1
 Try \`$0 --help' for more information." >&5
 echo "$as_me: error: ambiguous option: $1
 Try \`$0 --help' for more information." >&2;}
@@ -10912,12 +10920,12 @@ Try \`$0 --help' for more information." >&2;}
   'include/Inventor/system/inttypes.h' ) CONFIG_HEADERS="$CONFIG_HEADERS include/Inventor/system/inttypes.h" ;;
 
   # This is an error.
-  -*) { { echo "$as_me:10915: error: unrecognized option: $1
+  -*) { { echo "$as_me:10923: error: unrecognized option: $1
 Try \`$0 --help' for more information." >&5
 echo "$as_me: error: unrecognized option: $1
 Try \`$0 --help' for more information." >&2;}
    { (exit 1); exit 1; }; } ;;
-  *) { { echo "$as_me:10920: error: invalid argument: $1" >&5
+  *) { { echo "$as_me:10928: error: invalid argument: $1" >&5
 echo "$as_me: error: invalid argument: $1" >&2;}
    { (exit 1); exit 1; }; };;
   esac
@@ -10931,7 +10939,7 @@ cat >&5 << _ACEOF
 ## Running config.status.  ##
 ## ----------------------- ##
 
-This file was extended by $as_me (Coin v0.9.99) 2.50, executed with
+This file was extended by $as_me (Coin 0.9.99) 2.50, executed with
   > $ac_cs_invocation
 on `(hostname || uname -n) 2>/dev/null | sed 1q`
 
@@ -11121,6 +11129,8 @@ s,@COIN_HACKING_LIBDIRS@,$COIN_HACKING_LIBDIRS,;t t
 s,@coin_build_dir@,$coin_build_dir,;t t
 s,@coin_src_dir@,$coin_src_dir,;t t
 s,@LIBFLAGS@,$LIBFLAGS,;t t
+s,@BUILD_WITH_MSVC_TRUE@,$BUILD_WITH_MSVC_TRUE,;t t
+s,@BUILD_WITH_MSVC_FALSE@,$BUILD_WITH_MSVC_FALSE,;t t
 s,@coin_configure_date@,$coin_configure_date,;t t
 CEOF
 
@@ -11236,7 +11246,7 @@ done; }
   esac
 
   if test x"$ac_file" != x-; then
-    { echo "$as_me:11239: creating $ac_file" >&5
+    { echo "$as_me:11249: creating $ac_file" >&5
 echo "$as_me: creating $ac_file" >&6;}
     rm -f "$ac_file"
   fi
@@ -11254,7 +11264,7 @@ echo "$as_me: creating $ac_file" >&6;}
       -) echo $tmp/stdin ;;
       [\\/$]*)
          # Absolute (can't be DOS-style, as IFS=:)
-         test -f "$f" || { { echo "$as_me:11257: error: cannot find input file: $f" >&5
+         test -f "$f" || { { echo "$as_me:11267: error: cannot find input file: $f" >&5
 echo "$as_me: error: cannot find input file: $f" >&2;}
    { (exit 1); exit 1; }; }
          echo $f;;
@@ -11267,7 +11277,7 @@ echo "$as_me: error: cannot find input file: $f" >&2;}
            echo $srcdir/$f
          else
            # /dev/null tree
-           { { echo "$as_me:11270: error: cannot find input file: $f" >&5
+           { { echo "$as_me:11280: error: cannot find input file: $f" >&5
 echo "$as_me: error: cannot find input file: $f" >&2;}
    { (exit 1); exit 1; }; }
          fi;;
@@ -11328,7 +11338,7 @@ for ac_file in : $CONFIG_HEADERS; do test "x$ac_file" = x: && continue
   * )   ac_file_in=$ac_file.in ;;
   esac
 
-  test x"$ac_file" != x- && { echo "$as_me:11331: creating $ac_file" >&5
+  test x"$ac_file" != x- && { echo "$as_me:11341: creating $ac_file" >&5
 echo "$as_me: creating $ac_file" >&6;}
 
   # First look for the input files in the build tree, otherwise in the
@@ -11339,7 +11349,7 @@ echo "$as_me: creating $ac_file" >&6;}
       -) echo $tmp/stdin ;;
       [\\/$]*)
          # Absolute (can't be DOS-style, as IFS=:)
-         test -f "$f" || { { echo "$as_me:11342: error: cannot find input file: $f" >&5
+         test -f "$f" || { { echo "$as_me:11352: error: cannot find input file: $f" >&5
 echo "$as_me: error: cannot find input file: $f" >&2;}
    { (exit 1); exit 1; }; }
          echo $f;;
@@ -11352,7 +11362,7 @@ echo "$as_me: error: cannot find input file: $f" >&2;}
            echo $srcdir/$f
          else
            # /dev/null tree
-           { { echo "$as_me:11355: error: cannot find input file: $f" >&5
+           { { echo "$as_me:11365: error: cannot find input file: $f" >&5
 echo "$as_me: error: cannot find input file: $f" >&2;}
    { (exit 1); exit 1; }; }
          fi;;
@@ -11469,7 +11479,7 @@ cat >>$CONFIG_STATUS <<\EOF
   rm -f $tmp/in
   if test x"$ac_file" != x-; then
     if cmp -s $ac_file $tmp/config.h 2>/dev/null; then
-      { echo "$as_me:11472: $ac_file is unchanged" >&5
+      { echo "$as_me:11482: $ac_file is unchanged" >&5
 echo "$as_me: $ac_file is unchanged" >&6;}
     else
       ac_dir=`$as_expr X"$ac_file" : 'X\(.*[^/]\)//*[^/][^/]*/*$' \| \
