Bootstrap.

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -19458,14 +19458,27 @@ ac_compiler_gnu=$ac_cv_c_compiler_gnu
 
 ## See which way the compiler knows the name of the current function. ####
 
-echo "$as_me:$LINENO: checking for function name variable" >&5
-echo $ECHO_N "checking for function name variable... $ECHO_C" >&6
-if test "${sim_cv_var_functionname+set}" = set; then
-  echo $ECHO_N "(cached) $ECHO_C" >&6
-else
+  ac_ext=cc
+ac_cpp='$CXXCPP $CPPFLAGS'
+ac_compile='$CXX -c $CXXFLAGS $CPPFLAGS conftest.$ac_ext >&5'
+ac_link='$CXX -o conftest$ac_exeext $CXXFLAGS $CPPFLAGS $LDFLAGS conftest.$ac_ext $LIBS >&5'
+ac_compiler_gnu=$ac_cv_cxx_compiler_gnu
 
-  # __func__ is the identifier used by compilers which are
-  # compliant with the C99 ISO/IEC 9899:1999 standard.
+
+echo "$as_me:$LINENO: checking for function name variable for CPP compiler" >&5
+echo $ECHO_N "checking for function name variable for CPP compiler... $ECHO_C" >&6
+sim_ac_var_functionname=
+
+# * __func__ is the identifier used by compilers which are
+#   compliant with the C99 ISO/IEC 9899:1999 standard.
+#
+# * GCC uses __PRETTY_FUNCTION__
+#
+# * FIXME: why was __FUNCTION__ added? for SGI MIPSpro, perhaps?
+#   20040902 mortene.
+
+for i in "__func__" "__PRETTY_FUNCTION__" "__FUNCTION__"; do
+if test -z "$sim_ac_var_functionname"; then
   cat >conftest.$ac_ext <<_ACEOF
 #line $LINENO "configure"
 /* confdefs.h.  */
@@ -19477,7 +19490,7 @@ cat >>conftest.$ac_ext <<_ACEOF
 int
 main ()
 {
-(void)printf("%s\n",__func__)
+(void)printf("%s\n", $i)
   ;
   return 0;
 }
@@ -19494,17 +19507,58 @@ if { (eval echo "$as_me:$LINENO: \"$ac_compile\"") >&5
   ac_status=$?
   echo "$as_me:$LINENO: \$? = $ac_status" >&5
   (exit $ac_status); }; }; then
-  sim_cv_var_functionname=__func__
+  sim_ac_var_functionname=$i
+
 else
   echo "$as_me: failed program was:" >&5
 sed 's/^/| /' conftest.$ac_ext >&5
 
-sim_cv_var_functionname=none
 fi
 rm -f conftest.$ac_objext conftest.$ac_ext
-  if test x"$sim_cv_var_functionname" = x"none"; then
-    # GCC uses __PRETTY_FUNCTION__
-    cat >conftest.$ac_ext <<_ACEOF
+fi
+done
+
+if test -z "$sim_ac_var_functionname"; then
+  echo "$as_me:$LINENO: result: none" >&5
+echo "${ECHO_T}none" >&6
+else
+  echo "$as_me:$LINENO: result: $sim_ac_var_functionname" >&5
+echo "${ECHO_T}$sim_ac_var_functionname" >&6
+
+cat >>confdefs.h <<_ACEOF
+#define HAVE_CPP_COMPILER_FUNCTION_NAME_VAR $sim_ac_var_functionname
+_ACEOF
+
+fi
+
+  ac_ext=c
+ac_cpp='$CPP $CPPFLAGS'
+ac_compile='$CC -c $CFLAGS $CPPFLAGS conftest.$ac_ext >&5'
+ac_link='$CC -o conftest$ac_exeext $CFLAGS $CPPFLAGS $LDFLAGS conftest.$ac_ext $LIBS >&5'
+ac_compiler_gnu=$ac_cv_c_compiler_gnu
+
+  ac_ext=c
+ac_cpp='$CPP $CPPFLAGS'
+ac_compile='$CC -c $CFLAGS $CPPFLAGS conftest.$ac_ext >&5'
+ac_link='$CC -o conftest$ac_exeext $CFLAGS $CPPFLAGS $LDFLAGS conftest.$ac_ext $LIBS >&5'
+ac_compiler_gnu=$ac_cv_c_compiler_gnu
+
+
+echo "$as_me:$LINENO: checking for function name variable for C compiler" >&5
+echo $ECHO_N "checking for function name variable for C compiler... $ECHO_C" >&6
+sim_ac_var_functionname=
+
+# * __func__ is the identifier used by compilers which are
+#   compliant with the C99 ISO/IEC 9899:1999 standard.
+#
+# * GCC uses __PRETTY_FUNCTION__
+#
+# * FIXME: why was __FUNCTION__ added? for SGI MIPSpro, perhaps?
+#   20040902 mortene.
+
+for i in "__func__" "__PRETTY_FUNCTION__" "__FUNCTION__"; do
+if test -z "$sim_ac_var_functionname"; then
+  cat >conftest.$ac_ext <<_ACEOF
 #line $LINENO "configure"
 /* confdefs.h.  */
 _ACEOF
@@ -19515,7 +19569,7 @@ cat >>conftest.$ac_ext <<_ACEOF
 int
 main ()
 {
-(void)printf("%s\n",__PRETTY_FUNCTION__)
+(void)printf("%s\n", $i)
   ;
   return 0;
 }
@@ -19532,83 +19586,36 @@ if { (eval echo "$as_me:$LINENO: \"$ac_compile\"") >&5
   ac_status=$?
   echo "$as_me:$LINENO: \$? = $ac_status" >&5
   (exit $ac_status); }; }; then
-  sim_cv_var_functionname=__PRETTY_FUNCTION__
+  sim_ac_var_functionname=$i
+
 else
   echo "$as_me: failed program was:" >&5
 sed 's/^/| /' conftest.$ac_ext >&5
 
-sim_cv_var_functionname=none
 fi
 rm -f conftest.$ac_objext conftest.$ac_ext
-  fi
-  if test x"$sim_cv_var_functionname" = x"none"; then
-    cat >conftest.$ac_ext <<_ACEOF
-#line $LINENO "configure"
-/* confdefs.h.  */
-_ACEOF
-cat confdefs.h >>conftest.$ac_ext
-cat >>conftest.$ac_ext <<_ACEOF
-/* end confdefs.h.  */
-#include <stdio.h>
-int
-main ()
-{
-(void)printf("%s\n",__FUNCTION__)
-  ;
-  return 0;
-}
-_ACEOF
-rm -f conftest.$ac_objext
-if { (eval echo "$as_me:$LINENO: \"$ac_compile\"") >&5
-  (eval $ac_compile) 2>&5
-  ac_status=$?
-  echo "$as_me:$LINENO: \$? = $ac_status" >&5
-  (exit $ac_status); } &&
-         { ac_try='test -s conftest.$ac_objext'
-  { (eval echo "$as_me:$LINENO: \"$ac_try\"") >&5
-  (eval $ac_try) 2>&5
-  ac_status=$?
-  echo "$as_me:$LINENO: \$? = $ac_status" >&5
-  (exit $ac_status); }; }; then
-  sim_cv_var_functionname=__FUNCTION__
+fi
+done
+
+if test -z "$sim_ac_var_functionname"; then
+  echo "$as_me:$LINENO: result: none" >&5
+echo "${ECHO_T}none" >&6
 else
-  echo "$as_me: failed program was:" >&5
-sed 's/^/| /' conftest.$ac_ext >&5
+  echo "$as_me:$LINENO: result: $sim_ac_var_functionname" >&5
+echo "${ECHO_T}$sim_ac_var_functionname" >&6
 
-sim_cv_var_functionname=none
-fi
-rm -f conftest.$ac_objext conftest.$ac_ext
-  fi
-fi
-echo "$as_me:$LINENO: result: $sim_cv_var_functionname" >&5
-echo "${ECHO_T}$sim_cv_var_functionname" >&6
-
-# FIXME: these can probably be contracted to a single test inside a loop.
-# 20010330 mortene.
-
-if test x"$sim_cv_var_functionname" = x"__func__"; then
-
-cat >>confdefs.h <<\_ACEOF
-#define HAVE_VAR___func__ 1
+cat >>confdefs.h <<_ACEOF
+#define HAVE_C_COMPILER_FUNCTION_NAME_VAR $sim_ac_var_functionname
 _ACEOF
 
 fi
 
-if test x"$sim_cv_var_functionname" = x"__PRETTY_FUNCTION__"; then
+  ac_ext=c
+ac_cpp='$CPP $CPPFLAGS'
+ac_compile='$CC -c $CFLAGS $CPPFLAGS conftest.$ac_ext >&5'
+ac_link='$CC -o conftest$ac_exeext $CFLAGS $CPPFLAGS $LDFLAGS conftest.$ac_ext $LIBS >&5'
+ac_compiler_gnu=$ac_cv_c_compiler_gnu
 
-cat >>confdefs.h <<\_ACEOF
-#define HAVE_VAR___PRETTY_FUNCTION__ 1
-_ACEOF
-
-fi
-
-if test x"$sim_cv_var_functionname" = x"__FUNCTION__"; then
-
-cat >>confdefs.h <<\_ACEOF
-#define HAVE_VAR___FUNCTION__ 1
-_ACEOF
-
-fi
 
 
 case $host_os in
@@ -31206,8 +31213,18 @@ fi
 
 
   # *******************************************************************
-  # ** Check what OpenGL->windowsystem bindings are available.
-  # *******************************************************************
+  # Check what OpenGL->windowsystem bindings are available.
+  #
+  # If WGL is available, we don't want AGL nor GLX, as that has the
+  # potential to cause harm: e.g. while we at one place in the code
+  # might use WGL to create a context, other places we might use GLX to
+  # make that same context current -- *kaboom*.
+  #
+  # (It is at least possible that both AGL and GLX are available at the
+  # same time, or WGL and GLX, since X11 is a portable window system.)
+  #
+  # This is why the tests below are nested, so we're guaranteed that only
+  # one of HAVE_AGL, HAVE_WGL and HAVE_GLX will be set:
 
 
 sim_ac_save_libs=$LIBS
@@ -31338,6 +31355,64 @@ _ACEOF
       LDFLAGS="$LDFLAGS $sim_ac_agl_ldflags"
       COIN_EXTRA_LDFLAGS="$COIN_EXTRA_LDFLAGS $sim_ac_agl_ldflags"
 
+  echo "$as_me:$LINENO: checking whether we can use AGL pBuffers" >&5
+echo $ECHO_N "checking whether we can use AGL pBuffers... $ECHO_C" >&6
+if test "${sim_cv_agl_pbuffer_avail+set}" = set; then
+  echo $ECHO_N "(cached) $ECHO_C" >&6
+else
+  cat >conftest.$ac_ext <<_ACEOF
+#line $LINENO "configure"
+/* confdefs.h.  */
+_ACEOF
+cat confdefs.h >>conftest.$ac_ext
+cat >>conftest.$ac_ext <<_ACEOF
+/* end confdefs.h.  */
+ #include <AGL/agl.h>
+int
+main ()
+{
+AGLPbuffer pbuffer;
+  ;
+  return 0;
+}
+_ACEOF
+rm -f conftest.$ac_objext conftest$ac_exeext
+if { (eval echo "$as_me:$LINENO: \"$ac_link\"") >&5
+  (eval $ac_link) 2>&5
+  ac_status=$?
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); } &&
+         { ac_try='test -s conftest$ac_exeext'
+  { (eval echo "$as_me:$LINENO: \"$ac_try\"") >&5
+  (eval $ac_try) 2>&5
+  ac_status=$?
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); }; }; then
+  sim_cv_agl_pbuffer_avail=yes
+else
+  echo "$as_me: failed program was:" >&5
+sed 's/^/| /' conftest.$ac_ext >&5
+
+sim_cv_agl_pbuffer_avail=no
+fi
+rm -f conftest.$ac_objext conftest$ac_exeext conftest.$ac_ext
+fi
+echo "$as_me:$LINENO: result: $sim_cv_agl_pbuffer_avail" >&5
+echo "${ECHO_T}$sim_cv_agl_pbuffer_avail" >&6
+
+  if test x"$sim_cv_agl_pbuffer_avail" = xyes; then
+
+
+cat >>confdefs.h <<_ACEOF
+#define HAVE_AGL_PBUFFER 1
+_ACEOF
+
+
+  else
+    :
+  fi
+
+
 else
 
 
@@ -31421,65 +31496,7 @@ fi
 fi
 
 
-
-  echo "$as_me:$LINENO: checking whether we can use AGL pBuffers" >&5
-echo $ECHO_N "checking whether we can use AGL pBuffers... $ECHO_C" >&6
-if test "${sim_cv_agl_pbuffer_avail+set}" = set; then
-  echo $ECHO_N "(cached) $ECHO_C" >&6
-else
-  cat >conftest.$ac_ext <<_ACEOF
-#line $LINENO "configure"
-/* confdefs.h.  */
-_ACEOF
-cat confdefs.h >>conftest.$ac_ext
-cat >>conftest.$ac_ext <<_ACEOF
-/* end confdefs.h.  */
- #include <AGL/agl.h>
-int
-main ()
-{
-AGLPbuffer pbuffer;
-  ;
-  return 0;
-}
-_ACEOF
-rm -f conftest.$ac_objext conftest$ac_exeext
-if { (eval echo "$as_me:$LINENO: \"$ac_link\"") >&5
-  (eval $ac_link) 2>&5
-  ac_status=$?
-  echo "$as_me:$LINENO: \$? = $ac_status" >&5
-  (exit $ac_status); } &&
-         { ac_try='test -s conftest$ac_exeext'
-  { (eval echo "$as_me:$LINENO: \"$ac_try\"") >&5
-  (eval $ac_try) 2>&5
-  ac_status=$?
-  echo "$as_me:$LINENO: \$? = $ac_status" >&5
-  (exit $ac_status); }; }; then
-  sim_cv_agl_pbuffer_avail=yes
-else
-  echo "$as_me: failed program was:" >&5
-sed 's/^/| /' conftest.$ac_ext >&5
-
-sim_cv_agl_pbuffer_avail=no
-fi
-rm -f conftest.$ac_objext conftest$ac_exeext conftest.$ac_ext
-fi
-echo "$as_me:$LINENO: result: $sim_cv_agl_pbuffer_avail" >&5
-echo "${ECHO_T}$sim_cv_agl_pbuffer_avail" >&6
-
-  if test x"$sim_cv_agl_pbuffer_avail" = xyes; then
-
-
-cat >>confdefs.h <<_ACEOF
-#define HAVE_AGL_PBUFFER 1
-_ACEOF
-
-
-  else
-    :
-  fi
-
-
+  # *******************************************************************
 
   if $enable_superglu; then
 
