Bugfix, set up CPPFLAGS etc for static version of the lib.

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -11525,9 +11525,7 @@ fi
 if $sim_ac_build_library; then
   if $BUILD_WITH_MSVC; then
     if $COIN_STATIC; then
-      # forgot to include this case in SbBasic.h.in :(
-      CPPFLAGS="-DCOIN_NOT_DLL $CPPFLAGS"
-      # COIN_EXTRA_CPPFLAGS is set up further down
+      COIN_EXTRA_CPPFLAGS="$COIN_EXTRA_CPPFLAGS -DCOIN_NOT_DLL"
     else
       CPPFLAGS="-DCOIN_MAKE_DLL $CPPFLAGS"
       COIN_EXTRA_CPPFLAGS="$COIN_EXTRA_CPPFLAGS -DCOIN_DLL"
@@ -11545,9 +11543,6 @@ fi
 
       LIBFLAGS="-LIB"
       LIBFLAGS="$LIBFLAGS /OUT:coin$COIN_MAJOR_VERSION$SUFFIX.lib"
-      COIN_EXTRA_CPPFLAGS="-I$includedir -DCOIN_NOT_DLL"
-      COIN_EXTRA_LDFLAGS="-L$libdir"
-      COIN_EXTRA_LIBS=
     else
       LIBFLAGS="-DLL /INCREMENTAL:NO"
       case $enable_symbols in
@@ -11696,7 +11691,7 @@ DEFS=-DHAVE_CONFIG_H
 : ${CONFIG_STATUS=./config.status}
 ac_clean_files_save=$ac_clean_files
 ac_clean_files="$ac_clean_files $CONFIG_STATUS"
-{ echo "$as_me:11699: creating $CONFIG_STATUS" >&5
+{ echo "$as_me:11694: creating $CONFIG_STATUS" >&5
 echo "$as_me: creating $CONFIG_STATUS" >&6;}
 cat >$CONFIG_STATUS <<_ACEOF
 #! $SHELL
@@ -11872,7 +11867,7 @@ cat >>$CONFIG_STATUS <<\EOF
     echo "$ac_cs_version"; exit 0 ;;
   --he | --h)
     # Conflict between --help and --header
-    { { echo "$as_me:11875: error: ambiguous option: $1
+    { { echo "$as_me:11870: error: ambiguous option: $1
 Try \`$0 --help' for more information." >&5
 echo "$as_me: error: ambiguous option: $1
 Try \`$0 --help' for more information." >&2;}
@@ -11891,7 +11886,7 @@ Try \`$0 --help' for more information." >&2;}
     ac_need_defaults=false;;
 
   # This is an error.
-  -*) { { echo "$as_me:11894: error: unrecognized option: $1
+  -*) { { echo "$as_me:11889: error: unrecognized option: $1
 Try \`$0 --help' for more information." >&5
 echo "$as_me: error: unrecognized option: $1
 Try \`$0 --help' for more information." >&2;}
@@ -11979,7 +11974,7 @@ do
   "default-1" ) CONFIG_COMMANDS="$CONFIG_COMMANDS default-1" ;;
   "default-2" ) CONFIG_COMMANDS="$CONFIG_COMMANDS default-2" ;;
   "include/config.h" ) CONFIG_HEADERS="$CONFIG_HEADERS include/config.h" ;;
-  *) { { echo "$as_me:11982: error: invalid argument: $ac_config_target" >&5
+  *) { { echo "$as_me:11977: error: invalid argument: $ac_config_target" >&5
 echo "$as_me: error: invalid argument: $ac_config_target" >&2;}
    { (exit 1); exit 1; }; };;
   esac
@@ -12271,7 +12266,7 @@ done; }
   esac
 
   if test x"$ac_file" != x-; then
-    { echo "$as_me:12274: creating $ac_file" >&5
+    { echo "$as_me:12269: creating $ac_file" >&5
 echo "$as_me: creating $ac_file" >&6;}
     rm -f "$ac_file"
   fi
@@ -12289,7 +12284,7 @@ echo "$as_me: creating $ac_file" >&6;}
       -) echo $tmp/stdin ;;
       [\\/$]*)
          # Absolute (can't be DOS-style, as IFS=:)
-         test -f "$f" || { { echo "$as_me:12292: error: cannot find input file: $f" >&5
+         test -f "$f" || { { echo "$as_me:12287: error: cannot find input file: $f" >&5
 echo "$as_me: error: cannot find input file: $f" >&2;}
    { (exit 1); exit 1; }; }
          echo $f;;
@@ -12302,7 +12297,7 @@ echo "$as_me: error: cannot find input file: $f" >&2;}
            echo $srcdir/$f
          else
            # /dev/null tree
-           { { echo "$as_me:12305: error: cannot find input file: $f" >&5
+           { { echo "$as_me:12300: error: cannot find input file: $f" >&5
 echo "$as_me: error: cannot find input file: $f" >&2;}
    { (exit 1); exit 1; }; }
          fi;;
@@ -12363,7 +12358,7 @@ for ac_file in : $CONFIG_HEADERS; do test "x$ac_file" = x: && continue
   * )   ac_file_in=$ac_file.in ;;
   esac
 
-  test x"$ac_file" != x- && { echo "$as_me:12366: creating $ac_file" >&5
+  test x"$ac_file" != x- && { echo "$as_me:12361: creating $ac_file" >&5
 echo "$as_me: creating $ac_file" >&6;}
 
   # First look for the input files in the build tree, otherwise in the
@@ -12374,7 +12369,7 @@ echo "$as_me: creating $ac_file" >&6;}
       -) echo $tmp/stdin ;;
       [\\/$]*)
          # Absolute (can't be DOS-style, as IFS=:)
-         test -f "$f" || { { echo "$as_me:12377: error: cannot find input file: $f" >&5
+         test -f "$f" || { { echo "$as_me:12372: error: cannot find input file: $f" >&5
 echo "$as_me: error: cannot find input file: $f" >&2;}
    { (exit 1); exit 1; }; }
          echo $f;;
@@ -12387,7 +12382,7 @@ echo "$as_me: error: cannot find input file: $f" >&2;}
            echo $srcdir/$f
          else
            # /dev/null tree
-           { { echo "$as_me:12390: error: cannot find input file: $f" >&5
+           { { echo "$as_me:12385: error: cannot find input file: $f" >&5
 echo "$as_me: error: cannot find input file: $f" >&2;}
    { (exit 1); exit 1; }; }
          fi;;
@@ -12504,7 +12499,7 @@ cat >>$CONFIG_STATUS <<\EOF
   rm -f $tmp/in
   if test x"$ac_file" != x-; then
     if cmp -s $ac_file $tmp/config.h 2>/dev/null; then
-      { echo "$as_me:12507: $ac_file is unchanged" >&5
+      { echo "$as_me:12502: $ac_file is unchanged" >&5
 echo "$as_me: $ac_file is unchanged" >&6;}
     else
       ac_dir=`$as_expr X"$ac_file" : 'X\(.*[^/]\)//*[^/][^/]*/*$' \| \
