zlib detection.

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -1076,6 +1076,7 @@ Optional Packages:
   --with-simage=DIR       use simage for loading texture files
   --with-openal=PATH      enable/disable OpenAL support
   --with-freetype=PATH    enable/disable Freetype support
+  --with-zlib=PATH        enable/disable zlib support
   --with-x                use the X Window System
   --with-mesa             prefer MesaGL (if found) over OpenGL [default=yes]
   --with-opengl=DIR       OpenGL/Mesa installation directory
@@ -4620,7 +4621,7 @@ test "x$enable_libtool_lock" != xno && enable_libtool_lock=yes
 case $host in
 *-*-irix6*)
   # Find out which ABI we are using.
-  echo '#line 4623 "configure"' > conftest.$ac_ext
+  echo '#line 4624 "configure"' > conftest.$ac_ext
   if { (eval echo "$as_me:$LINENO: \"$ac_compile\"") >&5
   (eval $ac_compile) 2>&5
   ac_status=$?
@@ -5156,7 +5157,7 @@ chmod -w .
 save_CFLAGS="$CFLAGS"
 CFLAGS="$CFLAGS -o out/conftest2.$ac_objext"
 compiler_c_o=no
-if { (eval echo configure:5159: \"$ac_compile\") 1>&5; (eval $ac_compile) 2>out/conftest.err; } && test -s out/conftest2.$ac_objext; then
+if { (eval echo configure:5160: \"$ac_compile\") 1>&5; (eval $ac_compile) 2>out/conftest.err; } && test -s out/conftest2.$ac_objext; then
   # The compiler can only warn and ignore the option if not recognized
   # So say no if there are warnings
   if test -s out/conftest.err; then
@@ -6950,7 +6951,7 @@ else
     lt_dlunknown=0; lt_dlno_uscore=1; lt_dlneed_uscore=2
   lt_status=$lt_dlunknown
   cat > conftest.$ac_ext <<EOF
-#line 6953 "configure"
+#line 6954 "configure"
 #include "confdefs.h"
 
 #if HAVE_DLFCN_H
@@ -7048,7 +7049,7 @@ else
     lt_dlunknown=0; lt_dlno_uscore=1; lt_dlneed_uscore=2
   lt_status=$lt_dlunknown
   cat > conftest.$ac_ext <<EOF
-#line 7051 "configure"
+#line 7052 "configure"
 #include "confdefs.h"
 
 #if HAVE_DLFCN_H
@@ -17825,6 +17826,154 @@ echo "${ECHO_T}no" >&6
 
 fi
 rm -f conftest.$ac_objext conftest$ac_exeext conftest.$ac_ext
+
+# *******************************************************************
+# * Handle the detection and inclusion of zlib
+# *******************************************************************
+: ${sim_ac_have_libzlib=false}
+echo "$as_me:$LINENO: checking for zlib" >&5
+echo $ECHO_N "checking for zlib... $ECHO_C" >&6
+
+# Check whether --with-zlib or --without-zlib was given.
+if test "${with_zlib+set}" = set; then
+  withval="$with_zlib"
+  case $withval in
+  yes | "") sim_ac_want_libzlib=true ;;
+  no)       sim_ac_want_libzlib=false ;;
+  *)        sim_ac_want_libzlib=true
+            sim_ac_libzlib_path=$withval ;;
+  esac
+else
+  sim_ac_want_libzlib=true
+fi;
+case $sim_ac_want_libzlib in
+true)
+  $sim_ac_have_libzlib && break
+  sim_ac_libzlib_save_CPPFLAGS=$CPPFLAGS
+  sim_ac_libzlib_save_LDFLAGS=$LDFLAGS
+  sim_ac_libzlib_save_LIBS=$LIBS
+  sim_ac_libzlib_debug=false
+  test -n "`echo -- $CPPFLAGS $CFLAGS $CXXFLAGS | grep -- '-g\\>'`" &&
+    sim_ac_libzlib_debug=true
+  # test -z "$sim_ac_libzlib_path" -a x"$prefix" != xNONE &&
+  #   sim_ac_libzlib_path=$prefix
+  sim_ac_libzlib_name=z
+  if test -n "$sim_ac_libzlib_path"; then
+    for sim_ac_libzlib_candidate in \
+      `( ls $sim_ac_libzlib_path/lib/zlib*.lib;
+         ls $sim_ac_libzlib_path/lib/zlib*d.lib ) 2>/dev/null`
+    do
+      case $sim_ac_libzlib_candidate in
+      *d.lib)
+        $sim_ac_libzlib_debug &&
+          sim_ac_libzlib_name=`basename $sim_ac_libzlib_candidate .lib` ;;
+      *.lib)
+        sim_ac_libzlib_name=`basename $sim_ac_libzlib_candidate .lib` ;;
+      esac
+    done
+    sim_ac_libzlib_cppflags="-I$sim_ac_libzlib_path/include"
+    CPPFLAGS="$CPPFLAGS $sim_ac_libzlib_cppflags"
+    sim_ac_libzlib_ldflags="-L$sim_ac_libzlib_path/lib"
+    LDFLAGS="$LDFLAGS $sim_ac_libzlib_ldflags"
+    # unset sim_ac_libzlib_candidate
+    # unset sim_ac_libzlib_path
+  fi
+  sim_ac_libzlib_libs="-l$sim_ac_libzlib_name"
+  LIBS="$sim_ac_libzlib_libs $LIBS"
+  cat >conftest.$ac_ext <<_ACEOF
+#line $LINENO "configure"
+#include "confdefs.h"
+#include <zlib.h>
+#ifdef F77_DUMMY_MAIN
+#  ifdef __cplusplus
+     extern "C"
+#  endif
+   int F77_DUMMY_MAIN() { return 1; }
+#endif
+int
+main ()
+{
+(void)zlibVersion();
+  ;
+  return 0;
+}
+_ACEOF
+rm -f conftest.$ac_objext conftest$ac_exeext
+if { (eval echo "$as_me:$LINENO: \"$ac_link\"") >&5
+  (eval $ac_link) 2>&5
+  ac_status=$?
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); } &&
+         { ac_try='test -s conftest$ac_exeext'
+  { (eval echo "$as_me:$LINENO: \"$ac_try\"") >&5
+  (eval $ac_try) 2>&5
+  ac_status=$?
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); }; }; then
+  sim_ac_have_libzlib=true
+else
+  echo "$as_me: failed program was:" >&5
+cat conftest.$ac_ext >&5
+fi
+rm -f conftest.$ac_objext conftest$ac_exeext conftest.$ac_ext
+  CPPFLAGS=$sim_ac_libzlib_save_CPPFLAGS
+  LDFLAGS=$sim_ac_libzlib_save_LDFLAGS
+  LIBS=$sim_ac_libzlib_save_LIBS
+  # unset sim_ac_libzlib_debug
+  # unset sim_ac_libzlib_name
+  # unset sim_ac_libzlib_save_CPPFLAGS
+  # unset sim_ac_libzlib_save_LDFLAGS
+  # unset sim_ac_libzlib_save_LIBS
+  ;;
+esac
+if $sim_ac_want_libzlib; then
+  if $sim_ac_have_libzlib; then
+    echo "$as_me:$LINENO: result: success ($sim_ac_libzlib_libs)" >&5
+echo "${ECHO_T}success ($sim_ac_libzlib_libs)" >&6
+
+  COIN_EXTRA_CPPFLAGS="$COIN_EXTRA_CPPFLAGS $sim_ac_libzlib_cppflags"
+  COIN_EXTRA_LDFLAGS="$COIN_EXTRA_LDFLAGS $sim_ac_libzlib_ldflags"
+  COIN_EXTRA_LIBS="$sim_ac_libzlib_libs $COIN_EXTRA_LIBS"
+  CPPFLAGS="$CPPFLAGS $sim_ac_libzlib_cppflags"
+  LDFLAGS="$LDFLAGS $sim_ac_libzlib_ldflags"
+  LIBS="$sim_ac_libzlib_libs $LIBS"
+  if test x"${sim_ac_configuration_settings+set}" = x"set"; then
+  sim_ac_configuration_settings="$sim_ac_configuration_settings|zlib support:Yes, link-time binding"
+else
+  sim_ac_configuration_settings="zlib support:Yes, link-time binding"
+fi
+
+
+cat >>confdefs.h <<\_ACEOF
+#define HAVE_ZLIB 1
+_ACEOF
+
+
+  else
+    echo "$as_me:$LINENO: result: failure" >&5
+echo "${ECHO_T}failure" >&6
+
+  if test x"${sim_ac_configuration_settings+set}" = x"set"; then
+  sim_ac_configuration_settings="$sim_ac_configuration_settings|zlib support:No"
+else
+  sim_ac_configuration_settings="zlib support:No"
+fi
+
+
+  fi
+else
+  echo "$as_me:$LINENO: result: disabled" >&5
+echo "${ECHO_T}disabled" >&6
+
+  if test x"${sim_ac_configuration_settings+set}" = x"set"; then
+  sim_ac_configuration_settings="$sim_ac_configuration_settings|zlib support:No"
+else
+  sim_ac_configuration_settings="zlib support:No"
+fi
+
+
+fi
+# unset sim_ac_want_libzlib
 
 
 # *******************************************************************
